import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'about.commitments': 'Nossos Compromissos',
    'about.header': 'Sobre Microsoft Exchange',
    'about.hero_sub': 'Explore como a tecnologia Microsoft está capacitando pessoas em todo o mundo para criarem o futuro que desejam.',
    'about.hero_title': 'Acreditamos no que é possível.',
    'about.local_p1': 'Utilizadores em Angola podem agora aceder aos nossos serviços e integrar o ecossistema oficial da nossa empresa.',
    'about.local_title': 'Plataforma e Ecossistema Local',
    'about.mission_desc': 'Capacitar cada pessoa e cada organização no planeta a conquistar mais através da tecnologia.',
    'about.mission_title': 'Nossa Missão',
    'about.quote': '"Nossa jornada é sobre construir tecnologia para que outros possam construir mais tecnologia."',
    'about.rights': '© 2026 Microsoft Exchange. Todos os direitos reservados.',
    'about.stat_countries': 'Países',
    'about.stat_foundation': 'Fundação',
    'about.stat_licenses': 'Licenças',
    'about.stat_people': 'Pessoas',
    'about.vision_label': 'Visão Geral',
    'about.vision_p1': 'A Microsoft Exchange é uma força motriz na inovação tecnológica global. Evoluímos de uma empresa de software para uma líder em serviços de nuvem inteligente.',
    'about.vision_p2': 'Com avanços pioneiros em IA, oferecemos as ferramentas necessárias para que organizações transformem sua produtividade.',
    'about.vision_title': 'Liderando a transformação digital global.',
    'auth.btn_register': 'Registrar',
    'auth.captcha_error_empty': 'Por favor preencha a verificação do Captcha',
    'auth.captcha_error_wrong': 'Código Captcha incorreto. Tente novamente.',
    'auth.captcha_label': 'Validação Captcha',
    'auth.captcha_placeholder': 'Código captcha',
    'auth.create_one': 'Crie uma!',
    'auth.enter_password': 'Inserir senha',
    'auth.forgot_password': 'Esqueceu a senha?',
    'auth.has_account': 'Já tem uma conta?',
    'auth.invite_code': 'Código de Convite',
    'auth.invite_error_empty': 'Por favor insira o código de convite',
    'auth.invite_placeholder': 'Introduzir código (INV-XXXXX)',
    'auth.login': 'Entrar',
    'auth.no_account': 'Não tem uma conta?',
    'auth.password_error_complexity': 'A senha deve conter letras e números',
    'auth.password_error_empty': 'Por favor introduza a senha',
    'auth.password_error_length': 'A senha deve ter 8 dígitos ou mais',
    'auth.password_error_simple': 'Senha muito simples. Por favor, escolha uma senha mais segura.',
    'auth.password_error_wrong': 'Senha de login incorreta.',
    'auth.password_label': 'Senha',
    'auth.password_placeholder': 'Introduzir senha',
    'auth.password_signup_placeholder': 'Pelo menos 8 caracteres',
    'auth.phone_error_empty': 'Por favor insira o número',
    'auth.phone_error_format': 'Número inválido para o formato local',
    'auth.phone_error_invalid': 'Este número de telefone parece ser inválido',
    'auth.phone_error_length': 'O número deve possuir 9 dígitos',
    'auth.phone_label': 'Número de Telefone',
    'auth.phone_placeholder': 'Introduzir número (9XXXXXXXX)',
    'auth.signup': 'Cadastro',
    'auth.signup_success': 'Conta criada com sucesso!',
    'auth.signup_title': 'Criar conta',
    'auth.welcome_back': 'Bem-vindo de volta!',
    'auth.invite_error_length': 'O código de convite deve ter 10 dígitos numéricos.',
    'bank.add_new': '+ Adicionar um novo método de pagamento',
    'bank.bind': 'Vincular Banco',
    'bank.desc': 'Certifique-se de que os dados coincidem com o seu BI para evitar atrasos nos saques.',
    'bank.holder': 'Nome do Titular',
    'bank.holder_placeholder': 'Ex: João Manuel Silva',
    'bank.iban': 'IBAN Angolano',
    'bank.info_desc': 'Gerencie como você recebe fundos e verifique o status de verificação de suas contas.',
    'bank.info_title': 'Pagamento e cobrança',
    'bank.name': 'Banco',
    'bank.remove': 'Remover este método de pagamento',
    'bank.save_btn': 'Guardar Dados',
    'bank.security': 'Segurança e conformidade',
    'bank.security_desc': 'As informações da sua conta bancária são armazenadas de forma segura e criptografada. A Microsoft Exchange segue os padrões globais de conformidade financeira para garantir que suas transações sejam sempre protegidas.',
    'bank.select': 'Selecionar Instituição',
    'bank.title': 'Conta Bancária',
    'bank.verified': 'Verificado',
    'common.back': 'Voltar',
    'common.cancel': 'Cancelar',
    'common.close': 'Fechar',
    'common.confirm': 'Confirmar',
    'common.copied': 'Copiado',
    'common.copy': 'Copiar',
    'common.error': 'Erro',
    'common.loading': 'Carregando...',
    'common.next': 'Próximo',
    'common.prev': 'Anterior',
    'common.save': 'Guardar',
    'common.send': 'Enviar',
    'common.status': 'Estado',
    'common.success': 'Sucesso',
    'common.verified': 'Verificada',
    'common.warning': 'Aviso',
    'coupons.btn': 'Resgatar Agora',
    'coupons.error_invalid': 'Por favor, insira um código de cupom válido.',
    'coupons.hero_sub': 'Insira o código promocional fornecido pelo seu gerente ou nos grupos oficiais.',
    'coupons.hero_title': 'Ativar Bônus',
    'coupons.label': 'Código do Cupom',
    'coupons.placeholder': 'Introduza o código',
    'coupons.title': 'Resgate de Cupom',
    'faq.feedback_thanks': 'Agradecemos o seu comentário!',
    'faq.feedback_useful': 'Estas informações foram úteis?',
    'faq.header': 'Perguntas Frequentes',
    'faq.hero_sub': 'Encontre guias e respostas sobre a plataforma.',
    'faq.hero_title': 'Ajuda técnica',
    'faq.no': 'Não',
    'faq.q1': 'Como recarregar a minha conta?',
    'faq.q2': 'Como retirar os meus ganhos?',
    'faq.q3': 'Como completar a tarefa diária?',
    'faq.q4': 'Qual é a duração dos produtos?',
    'faq.q5': 'Como funciona a plataforma?',
    'faq.q6': 'Como usar o suporte?',
    'faq.q7': 'Ganhos por equipe?',
    'faq.yes': 'Sim',
    'history.activated_at': 'Ativada em',
    'history.backup_iso': 'MB',
    'history.completed': 'Concluído',
    'history.empty': 'Nenhuma licença ativa encontrada.',
    'history.empty_cat': 'Nenhuma atividade registrada nesta categoria.',
    'history.failed': 'Falhou',
    'history.filter_all': 'Apresentar Tudo (Visão Geral)',
    'history.filter_cat': 'Filtrar Categoria',
    'history.filter_coupon': 'Resgate de Cupons',
    'history.filter_income': 'Rendimentos Diários',
    'history.filter_recharge': 'Recargas de Saldo',
    'history.filter_team': 'Comissões & Bónus de Equipe',
    'history.filter_withdraw': 'Levantamentos',
    'history.filtered': 'Filtrado',
    'history.full_list': 'Lista Completa',
    'history.general_desc': 'Registro completo de suas operações financeiras na nuvem.',
    'history.general_title': 'Histórico de Atividades',
    'history.investment': 'Investimento',
    'history.license_id': 'Licença ID',
    'history.loading': 'Sincronizando com os servidores Microsoft...',
    'history.manage_server': 'Fazer Download Setup',
    'history.pending': 'Em Análise',
    'history.real_time': 'Tempo Real',
    'history.remaining': 'Duração Restante',
    'history.status': 'Status',
    'history.status_active': 'Ativo e Rendendo',
    'history.status_expired': 'Expirado',
    'history.syncing': 'Sincronizando Atividades...',
    'history.title': 'Minhas Licenças',
    'home.announcement.content1': 'Sua jornada rumo à independência financeira começa aqui. A Microsoft Exchange Tecnologia oferece a infraestrutura de nuvem mais segura e rentável do mercado angolano.',
    'home.announcement.content2': 'Ganhe bônus em 3 níveis convidando amigos e familiares para a nossa comunidade.',
    'home.announcement.content3': 'Junte-se ao nosso WhatsApp para provas de pagamento e suporte técnico prioritário.',
    'home.announcement.title1': 'Seja bem-vindo à Microsoft Exchange Angola',
    'home.announcement.title2': 'Sistema de Convites e Ganhos em Equipe',
    'home.announcement.title3': 'Comunidade Oficial Microsoft',
    'home.community_btn': 'Entrar na Comunidade',
    'home.doubts': 'Dúvidas?',
    'home.hero_sub': 'Comece sua jornada com a infraestrutura mais robusta do mercado.',
    'home.marquee': 'Bem-vindo à Microsoft Exchange Angola! Aproveite nossas ofertas exclusivas de servidores para impulsionar seu rendimento diário. Fique atento às nossas atualizações oficiais.',
    'home.news': 'Notícias',
    'home.secure': 'Seguro',
    'home.servers': 'Servidores',
    'home.social_proof': 'Provas de Saque',
    'home.support_btn': 'Acessar Suporte',
    'home.support_cta': 'Fale com o nosso suporte oficial Microsoft Exchange Partner disponível 24 horas.',
    'home.users': 'Usuários',
    'home.welcome_hero': 'Bem-vindo à Exchange Experience',
    'identity.auth_account': 'Autentique sua conta',
    'identity.auth_desc': 'Para garantir a segurança das transações, precisamos validar seus documentos oficiais.',
    'identity.back': 'Verso do BI',
    'identity.btn_send': 'Enviar para Verificação',
    'identity.front': 'Frente do BI',
    'identity.full_name': 'Nome Completo (Conforme BI)',
    'identity.id_number': 'Número do BI (14 Caracteres)',
    'identity.pgp': 'Proteção PGP Ativa',
    'identity.province': 'Província de Residência',
    'identity.status_pending': 'Verificação em Curso',
    'identity.status_pending_desc': 'Seus documentos foram recebidos e estão sendo analisados. Isso pode levar até 24h.',
    'identity.status_verified': 'Conta Verificada',
    'identity.status_verified_desc': 'Sua identidade foi autenticada com sucesso pelos servidores da Microsoft.',
    'identity.title': 'Verificação de Identidade',
    'invite.btn_share': 'Compartilhar Agora',
    'invite.code_label': 'Código de Convite',
    'invite.copy_toast': 'Copiado para a área de transferência!',
    'invite.link_label': 'Link de Convite',
    'invite.partnership': 'Rede de Parceria',
    'invite.team_btn': 'Minha Equipe',
    'invite.title': 'Convidar Amigos',
    'invite.toast_share': 'Opções de compartilhamento abertas!',
    'nav.home': 'Início',
    'nav.invite': 'Convidar',
    'nav.products': 'Produtos',
    'nav.profile': 'Perfil',
    'ops.btn_finished': 'Trabalho Concluído',
    'ops.btn_start': 'Iniciar Operações',
    'ops.collect': 'Coleta de Rendimentos',
    'ops.collect_sub': 'Ative seus servidores para obter lucros diários.',
    'ops.completed': 'Concluído',
    'ops.estimated': 'Rendimento Estimado',
    'ops.processing': 'Processando...',
    'ops.synchronized': 'Sincronizado',
    'ops.system_status': 'Status do Sistema',
    'ops.tasks_left': 'Tarefas Restantes',
    'ops.title': 'Iniciar Operações',
    'ops.waiting': 'Aguardando',
    'password.btn_update': 'Atualizar Senha',
    'password.confirm_label': 'Confirmar Nova Senha',
    'password.confirm_placeholder': 'Repetir a nova senha',
    'password.match_error': 'As novas senhas não coincidem!',
    'password.new_label': 'Nova Senha',
    'password.new_placeholder': 'Mínimo de 8 caracteres',
    'password.old_label': 'Senha Antiga',
    'password.old_placeholder': 'Confirmar senha atual',
    'password.protection': 'Proteção Criptografada',
    'password.recommendation': 'Recomendamos o uso de letras e números para maior segurança.',
    'password.security': 'Segurança da Conta',
    'password.success': 'Senha alterada com sucesso!',
    'password.title': 'Alterar Senha',
    'product.unit.day': 'dia',
    'product.unit.days': 'dias',
    'product.win10.desc': 'O padrão ouro da computação moderna. Versão Cloud Server com alta disponibilidade e recursos de servidor.',
    'product.win10.feat1': 'Menu Iniciar clássico',
    'product.win10.feat2': 'Cortana integrada',
    'product.win10.feat3': 'Microsoft Edge',
    'product.win10.feat4': 'Ambiente Cloud Dedicado',
    'product.win10.name': 'Windows 10',
    'product.win10.version': 'Cloud Server Base',
    'product.win11.desc': 'A última geração do Windows. Com recursos de IA integrados para maximizar seus lucros e eficiência.',
    'product.win11.feat1': 'Novo design centrado',
    'product.win11.feat2': 'Widgets integrados',
    'product.win11.feat3': 'Performance Superior',
    'product.win11.feat4': 'Copilot AI Pre-instalado',
    'product.win11.name': 'Windows 11',
    'product.win11.version': 'NextGen AI Core',
    'product.win7.desc': 'A experiência clássica do Windows 7, otimizada para nuvem. Estabilidade e performance para suas operações diárias.',
    'product.win7.feat1': 'Interface Aero Glass',
    'product.win7.feat2': 'Navegação rápida',
    'product.win7.feat3': 'Suporte a apps legados',
    'product.win7.feat4': 'Segurança avançada',
    'product.win7.name': 'Windows 7',
    'product.win7.version': 'Professional Edition',
    'product.win8.desc': 'Design moderno com blocos dinâmicos. O Windows 8 Enterprise oferece ferramentas de gestão poderosas para sua equipe.',
    'product.win8.feat1': 'Tela inicial dinâmica',
    'product.win8.feat2': 'Otimizado para toque',
    'product.win8.feat3': 'Multitarefa aprimorada',
    'product.win8.feat4': 'ISO oficial incluso',
    'product.win8.name': 'Windows 8',
    'product.win8.version': 'Enterprise V2',
    'products.activation': 'Ativação',
    'products.active_badge': 'Ativo',
    'products.available_now': 'Disponível para implantação imediata',
    'products.back_to_list': 'Voltar para Produtos',
    'products.btn_buy': 'Comprar',
    'products.buy_success': 'adquirida com sucesso!',
    'products.cloud_space': 'Espaço em Nuvem',
    'products.daily': 'Renda Diária',
    'products.daily_income': 'Renda Diária',
    'products.duration': 'Duração',
    'products.expiration': 'Expiração',
    'products.my_purchases': 'Minhas Compras',
    'products.not_found': 'Produto não encontrado',
    'products.os_version': 'Versão do SO',
    'products.overview': 'Visão Geral',
    'products.price': 'Preço',
    'products.product_id': 'ID do Produto',
    'products.secure_payment': 'Pagamento seguro processado via gateway regional.',
    'products.specs': 'Especificações',
    'products.sub': 'Licenças Microsoft de alta performance.',
    'products.tech_support_24h': 'Suporte técnico disponível 24h.',
    'products.title': 'Nuvem de Produtos',
    'products.total_price': 'Preço Final',
    'profile.about': 'Sobre Microsoft Exchange',
    'profile.auth': 'Autenticar Conta',
    'profile.balance': 'Saldo Total',
    'profile.bank_info': 'Informações Bancárias',
    'profile.bank_link': 'Vinculação Bancária',
    'profile.coupons': 'Resgatar Cupons',
    'profile.crypto_digital': 'Crypto Digital',
    'profile.history': 'Histórico Geral',
    'profile.logout': 'Sair da Conta',
    'profile.moeda_local': 'Moeda Local',
    'profile.operations': 'Iniciar Operações',
    'profile.recharge': 'Recarregar',
    'profile.recharge_usdt': 'Recarga USDT',
    'profile.settings': 'Configurações',
    'profile.team': 'Minha Equipe',
    'profile.title': 'Perfil do Utilizador',
    'profile.total_withdrawn': 'Total Retirada',
    'profile.user_cloud': 'Utilizador Microsoft Exchange',
    'profile.withdraw': 'Retirar',
    'recharge.amount': 'Valor da Recarga',
    'recharge.amount_requested': 'Montante a Transferir',
    'recharge.bank_dest': 'Banco Destinatário',
    'recharge.beneficiary': 'Favorecido Oficial',
    'recharge.btn_confirm': 'Confirmar Recarga',
    'recharge.btn_confirm_deposit': 'Confirmar Pagamento',
    'recharge.btn_finish': 'Finalizar Recarga',
    'recharge.confirm_title': 'Finalizar Depósito',
    'recharge.copy_toast': 'Copiado para a área de transferência!',
    'recharge.deposit_value': 'Valor do Depósito',
    'recharge.disclaimer': 'Ao clicar em finalizar, você declara estar ciente de que deve realizar a transferência via aplicativo do seu banco.',
    'recharge.history_title': 'Histórico de recargas',
    'recharge.iban_deposit': 'IBAN para Depósito',
    'recharge.iban_payment': 'IBAN de Pagamento',
    'recharge.manual_amount': 'Introduzir Valor Manual',
    'recharge.max_error': 'O valor máximo de recarga é de 1.000.000 Kz',
    'recharge.method': 'Método de Recarga',
    'recharge.min_error': 'O valor mínimo de recarga é de 3.000 Kz',
    'recharge.process_info': 'Geralmente entre 5 a 60 minutos após confirmação.',
    'recharge.process_time': 'Tempo de Processamento',
    'recharge.processing': 'Processamento Inteligente Ativo',
    'recharge.proof_label': 'Anexar Comprovativo',
    'recharge.security_badge': 'Segurança Certificada Microsoft Exchange',
    'recharge.select_bank_prompt': 'Por favor selecione um banco para carregar',
    'recharge.selected_bank': 'Banco Selecionado',
    'recharge.step_amount': 'Recarregar Saldo',
    'recharge.step_bank': 'Selecionar Banco',
    'recharge.step_details': 'Detalhes de Depósito',
    'recharge.suggested_amount': 'Sugestões',
    'recharge.title': 'Recarregar Conta',
    'recharge.upload_btn': 'Clique para anexar arquivo',
    'settings.active_status': 'Estado: Ativo',
    'settings.authenticate': 'Autenticar conta',
    'settings.change_password': 'Alterar senha',
    'settings.fixed_label': 'Fixo',
    'settings.help_title': 'Ajuda Exchange',
    'settings.hero_sub': 'Gerencie seus detalhes de segurança, verificação oficial e conexões de rede Microsoft Exchange.',
    'settings.identity_confirm': 'Confirmação de identidade institucional',
    'settings.invite_code': 'Código de convite',
    'settings.language': 'Idioma',
    'settings.logout': 'Encerrar Sessão',
    'settings.lost_access': 'Perdeu o acesso?',
    'settings.lost_access_sub': 'Recupere sua conta usando o processo oficial de verificação Microsoft.',
    'settings.network_info': 'Informações de Redes',
    'settings.phone': 'Telefone vinculado',
    'settings.recovery_btn': 'Iniciar Recuperação',
    'settings.security_personalization': 'Segurança e Personalização',
    'settings.support_btn': 'Falar com Suporte',
    'settings.support_tech': 'Suporte técnico',
    'settings.support_tech_sub': 'Contate nossa equipa especializada em infraestrutura de nuvem.',
    'settings.title': 'Configurações de Conta',
    'settings.update_credentials': 'Atualize suas credenciais de acesso',
    'social.amount_label': 'Valor Total do Saque (Kz)',
    'social.bonus_info': 'Publique sua prova e ganhe bônus de 100 Kz até 9.999 Kz.',
    'social.empty_proofs': 'Seja o primeiro a compartilhar seu sucesso e inspirar a comunidade!',
    'social.formats': 'Formatos suportados: JPG, PNG',
    'social.guarantee': 'Pagamentos Garantidos Microsoft Exchange',
    'social.help_others': 'Ajude outros usuários e ganhe bônus de visibilidade.',
    'social.history_info': 'Histórico de Pagamentos Verificados',
    'social.message_label': 'Sua Mensagem',
    'social.message_placeholder': 'Escreva um comentário...',
    'social.photo_label': 'Foto do Comprovativo',
    'social.proof1_comment': 'Recebido com sucesso! Microsoft Exchange realmente paga.',
    'social.proof2_comment': 'Saque rápido via IBAN. Recomendo a todos!',
    'social.proof_title': 'Prova Social',
    'social.received': 'Recebido',
    'social.received_value': 'Valor Recebido (Kz)',
    'social.see_proofs': 'Veja as provas de pagamentos reais dos nossos usuários Microsoft Exchange.',
    'social.send_btn': 'Enviar Prova Oficial',
    'social.send_proof': 'Enviar Comprovativo',
    'social.share_sub': 'Envie o comprovativo do seu saque para motivar a comunidade.',
    'social.share_success': 'Partilhe o seu sucesso!',
    'social.title': 'Provas Sociais',
    'social.transparency_wall': 'Mural da Transparência',
    'social.upload_btn': 'Carregar imagem do comprovativo',
    'social.your_comment': 'Seu Comentário',
    'support.encrypted_ticket': 'Ticket de Suporte Criptografado',
    'support.feedback_desc': 'Relate bugs, sugira melhorias ou peça ajuda técnica diretamente aos nossos desenvolvedores.',
    'support.feedback_question': 'Como podemos melhorar?',
    'support.feedback_title': 'Feedback Técnico',
    'support.header': 'Suporte Microsoft',
    'support.hero_title': 'Como podemos ajudar?',
    'support.manager_desc': 'Suporte VIP para líderes de equipe.',
    'support.manager_title': 'Gerente dedicado (Comunidade)',
    'support.msg_placeholder': 'Descreva seu problema ou sugestão aqui...',
    'support.search_placeholder': 'Digite aqui para pesquisar ajuda oficial...',
    'support.security_desc': 'Todas as interações de suporte são encriptadas e verificadas pela Microsoft.',
    'support.security_title': 'A sua segurança é a nossa prioridade',
    'support.send_msg': 'Enviar Mensagem',
    'support.tech_desc': 'Estamos aqui para ajudar 24 horas por dia.',
    'support.tech_title': 'Falar com Atendimento Técnico',
    'support.whatsapp_desc': 'Comunidade oficial de investidores e bônus.',
    'support.whatsapp_title': 'Entre no Grupo de WhatsApp',
    'support.your_msg': 'Sua Mensagem',
    'team.active': 'Ativo',
    'team.empty': 'A aguardar novos membros',
    'team.header': 'Minha Equipa',
    'team.inactive': 'Inativo',
    'team.level1': '1º Nível',
    'team.level2': '2º Nível',
    'team.level3': '3º Nível',
    'team.member_since': 'Membro desde',
    'team.search_placeholder': 'Procurar membro...',
    'team.stats_com': 'Comissões de Equipa',
    'team.stats_total': 'Membros Totais',
    'withdraw.amount': 'Valor da Retirada',
    'withdraw.amount_placeholder': 'Introduzir valor (Mín. 3.000 Kz)',
    'withdraw.bank_acc': 'Conta Bancária',
    'withdraw.bank_required': 'Por favor, cadastre uma conta bancária primeiro.',
    'withdraw.btn_request': 'Solicitar',
    'withdraw.empty': 'Você ainda não realizou solicitações de retirada nesta conta.',
    'withdraw.est_payment': 'Estimativa de Pagamento',
    'withdraw.gross_amount': 'Valor Bruto',
    'withdraw.history_desc': 'Visualize o status e detalhes das suas solicitações de retirada.',
    'withdraw.history_title': 'Registro de retirada',
    'withdraw.info1': 'Processamento em 5-60 minutos após aprovação.',
    'withdraw.info2': 'Taxa de 14% para manutenção do ecossistema Microsoft Exchange.',
    'withdraw.info_title': 'Informações de Retirada',
    'withdraw.insufficient': 'Saldo insuficiente.',
    'withdraw.min_amount': 'O valor mínimo de saque é 3.000 Kz',
    'withdraw.net_amount': 'Valor Líquido',
    'withdraw.password': 'Senha de Login',
    'withdraw.req_date': 'Data da Solicitação',
    'withdraw.security_pass_placeholder': 'Introduzir senha de login',
    'withdraw.tax': 'Taxa de Serviço (14%)',
    'withdraw.time_error': 'Saques disponíveis apenas das 10h às 16h.',
    'withdraw.title': 'Solicitar Retirada',
    'withdraw.total_net': 'Total Líquido',
    'withdraw.until': 'Até',
    'withdraw.verify_required': 'Sua conta precisa estar verificada (BI aprovado) para realizar saques.',
  },
  en: {
    'about.commitments': 'Our Commitments',
    'about.header': 'About Microsoft Exchange',
    'about.hero_sub': 'Explore how Microsoft technology is empowering people around the world to create the future they want.',
    'about.hero_title': 'We believe in what\'s possible.',
    'about.local_p1': 'Users in Angola can now access our services and join our company\'s official ecosystem.',
    'about.local_title': 'Local Platform and Ecosystem',
    'about.mission_desc': 'Empower every person and every organization on the planet to achieve more through technology.',
    'about.mission_title': 'Our Mission',
    'about.quote': '"Our journey is about building technology so that others can build more technology."',
    'about.rights': '© 2026 Microsoft Exchange. All rights reserved.',
    'about.stat_countries': 'Countries',
    'about.stat_foundation': 'Foundation',
    'about.stat_licenses': 'Licenses',
    'about.stat_people': 'People',
    'about.vision_label': 'Overview',
    'about.vision_p1': 'Microsoft Exchange is a driving force in global technological innovation. We evolved from a software company to a leader in intelligent cloud services.',
    'about.vision_p2': 'With pioneering advances in AI, we offer the tools necessary for organizations to transform their productivity.',
    'about.vision_title': 'Leading global digital transformation.',
    'auth.btn_register': 'Register',
    'auth.captcha_error_empty': 'Please fill in the CAPTCHA verification',
    'auth.captcha_error_wrong': 'Incorrect CAPTCHA code. Try again.',
    'auth.captcha_label': 'Captcha Validation',
    'auth.captcha_placeholder': 'Captcha code',
    'auth.create_one': 'Create one!',
    'auth.enter_password': 'Enter password',
    'auth.forgot_password': 'Forgot password?',
    'auth.has_account': 'Already have an account?',
    'auth.invite_code': 'Invite Code',
    'auth.invite_error_empty': 'Please enter the invite code',
    'auth.invite_placeholder': 'Enter code (INV-XXXXX)',
    'auth.login': 'Sign in',
    'auth.password_error_complexity': 'Password must contain letters and numbers',
    'auth.password_error_empty': 'Please enter the password',
    'auth.password_error_length': 'Password must have 8 or more characters',
    'auth.password_error_simple': 'Password too simple. Please choose a more secure password.',
    'auth.password_error_wrong': 'Incorrect login password.',
    'auth.password_label': 'Password',
    'auth.password_placeholder': 'Enter password',
    'auth.password_signup_placeholder': 'At least 8 characters',
    'auth.phone_error_empty': 'Please enter the number',
    'auth.phone_error_format': 'Invalid number for local format',
    'auth.phone_error_invalid': 'This phone number seems invalid',
    'auth.phone_error_length': 'Number must have 9 digits',
    'auth.phone_label': 'Phone Number',
    'auth.phone_placeholder': 'Enter number (9XXXXXXXX)',
    'auth.signup': 'Sign up',
    'auth.signup_success': 'Account created successfully!',
    'auth.signup_title': 'Create account',
    'auth.welcome_back': 'Welcome back!',
    'auth.invite_error_length': 'Invite code must have 10 numeric digits.',
    'bank.add_new': '+ Add a new payment method',
    'bank.bind': 'Bind Bank',
    'bank.desc': 'Make sure the data matches your ID to avoid withdrawal delays.',
    'bank.holder': 'Account Holder Name',
    'bank.holder_placeholder': 'Ex: John Doe',
    'bank.iban': 'Angolan IBAN',
    'bank.info_desc': 'Manage how you receive funds and check the verification status of your accounts.',
    'bank.info_title': 'Payment and billing',
    'bank.name': 'Bank',
    'bank.remove': 'Remove this payment method',
    'bank.save_btn': 'Save Data',
    'bank.security': 'Security and compliance',
    'bank.security_desc': 'Your bank account information is stored securely and encrypted. Microsoft Exchange follows global financial compliance standards to ensure your transactions are always protected.',
    'bank.select': 'Select Institution',
    'bank.title': 'Bank Account',
    'bank.verified': 'Verified',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.copied': 'Copied',
    'common.copy': 'Copy',
    'common.error': 'Error',
    'common.loading': 'Loading...',
    'common.next': 'Next',
    'common.prev': 'Previous',
    'common.save': 'Save',
    'common.send': 'Send',
    'common.status': 'Status',
    'common.success': 'Success',
    'common.verified': 'Verified',
    'common.warning': 'Warning',
    'coupons.btn': 'Redeem Now',
    'coupons.error_invalid': 'Please enter a valid coupon code.',
    'coupons.hero_sub': 'Enter the promo code provided by your manager or in official groups.',
    'coupons.hero_title': 'Activate Bonus',
    'coupons.label': 'Coupon Code',
    'coupons.placeholder': 'Enter the code',
    'coupons.title': 'Coupon Redemption',
    'faq.feedback_thanks': 'Thank you for your feedback!',
    'faq.feedback_useful': 'Was this information useful?',
    'faq.header': 'Frequently Asked Questions',
    'faq.hero_sub': 'Find guides and answers about the platform.',
    'faq.hero_title': 'Technical Help',
    'faq.no': 'No',
    'faq.q1': 'How to recharge my account?',
    'faq.q2': 'How to withdraw my earnings?',
    'faq.q3': 'How to complete the daily task?',
    'faq.q4': 'What is the duration of products?',
    'faq.q5': 'How does the platform work?',
    'faq.q6': 'How to use support?',
    'faq.q7': 'Team earnings?',
    'faq.yes': 'Yes',
    'history.activated_at': 'Activated on',
    'history.backup_iso': 'MB',
    'history.completed': 'Completed',
    'history.empty': 'No active licenses found.',
    'history.empty_cat': 'No activity registered in this category.',
    'history.failed': 'Failed',
    'history.filter_all': 'Show All (Overview)',
    'history.filter_cat': 'Filter Category',
    'history.filter_coupon': 'Coupon Redemption',
    'history.filter_income': 'Daily Incomes',
    'history.filter_recharge': 'Balance Recharges',
    'history.filter_team': 'Team Commissions & Bonuses',
    'history.filter_withdraw': 'Withdrawals',
    'history.filtered': 'Filtered',
    'history.full_list': 'Full List',
    'history.general_desc': 'Complete record of your cloud financial operations.',
    'history.general_title': 'Activity History',
    'history.investment': 'Investment',
    'history.license_id': 'License ID',
    'history.loading': 'Synchronizing with Microsoft servers...',
    'history.manage_server': 'Download Setup',
    'history.pending': 'Under Review',
    'history.real_time': 'Real Time',
    'history.remaining': 'Remaining Duration',
    'history.status': 'Status',
    'history.status_active': 'Active & Earning',
    'history.status_expired': 'Expired',
    'history.syncing': 'Syncing Activities...',
    'history.title': 'My Licenses',
    'home.announcement.content1': 'Your journey to financial independence starts here. Microsoft Exchange Technology offers the most secure and profitable cloud infrastructure.',
    'home.announcement.content2': 'Earn bonuses on 3 levels by inviting friends and family to our community.',
    'home.announcement.content3': 'Join our WhatsApp for proof of payment and priority technical support.',
    'home.announcement.title1': 'Welcome to Microsoft Exchange Angola',
    'home.announcement.title2': 'Invite System and Team Earnings',
    'home.announcement.title3': 'Official Microsoft Community',
    'home.community_btn': 'Join Community',
    'home.doubts': 'Any Doubts?',
    'home.hero_sub': 'Start your journey with the most robust infrastructure on the market.',
    'home.marquee': 'Welcome to Microsoft Exchange Angola! Enjoy our exclusive server offers to boost your daily yield. Stay tuned for our official updates.',
    'home.news': 'News',
    'home.secure': 'Secure',
    'home.servers': 'Servers',
    'home.social_proof': 'Withdrawal Proofs',
    'home.support_btn': 'Access Support',
    'home.support_cta': 'Talk to our official Microsoft Exchange Partner support available 24 hours.',
    'home.users': 'Users',
    'home.welcome_hero': 'Welcome to Exchange Experience',
    'identity.auth_account': 'Authenticate your account',
    'identity.auth_desc': 'To ensure transaction security, we need to validate your official documents.',
    'identity.back': 'Back of ID',
    'identity.btn_send': 'Send for Verification',
    'identity.front': 'Front of ID',
    'identity.full_name': 'Full Name (As on ID)',
    'identity.id_number': 'ID Number (14 Characters)',
    'identity.pgp': 'PGP Protection Active',
    'identity.province': 'Province of Residence',
    'identity.status_pending': 'Verification in Progress',
    'identity.status_pending_desc': 'Your documents have been received and are being analyzed. This can take up to 24h.',
    'identity.status_verified': 'Verified Account',
    'identity.status_verified_desc': 'Your identity was successfully authenticated by Microsoft servers.',
    'identity.title': 'Identity Verification',
    'invite.btn_share': 'Share Now',
    'invite.code_label': 'Invite Code',
    'invite.copy_toast': 'Copied to clipboard!',
    'invite.link_label': 'Invite Link',
    'invite.partnership': 'Partnership Network',
    'invite.team_btn': 'My Team',
    'invite.title': 'Invite Friends',
    'invite.toast_share': 'Sharing options opened!',
    'nav.home': 'Home',
    'nav.invite': 'Invite',
    'nav.products': 'Products',
    'nav.profile': 'Profile',
    'ops.btn_finished': 'Work Completed',
    'ops.btn_start': 'Start Operations',
    'ops.collect': 'Earnings Collection',
    'ops.collect_sub': 'Activate your servers to obtain daily profits.',
    'ops.completed': 'Completed',
    'ops.estimated': 'Estimated Yield',
    'ops.processing': 'Processing...',
    'ops.synchronized': 'Synchronized',
    'ops.system_status': 'System Status',
    'ops.tasks_left': 'Tasks Remaining',
    'ops.title': 'Start Operations',
    'ops.waiting': 'Waiting',
    'password.btn_update': 'Update Password',
    'password.confirm_label': 'Confirm New Password',
    'password.confirm_placeholder': 'Repeat new password',
    'password.match_error': 'New passwords do not match!',
    'password.new_label': 'New Password',
    'password.new_placeholder': 'Minimum 8 characters',
    'password.old_label': 'Old Password',
    'password.old_placeholder': 'Confirm current password',
    'password.protection': 'Encrypted Protection',
    'password.recommendation': 'We recommend using letters and numbers for added security.',
    'password.security': 'Account Security',
    'password.success': 'Password changed successfully!',
    'password.title': 'Change Password',
    'product.unit.day': 'day',
    'product.unit.days': 'days',
    'product.win10.desc': 'The gold standard of modern computing. Cloud Server version with high availability and server resources.',
    'product.win10.feat1': 'Classic Start Menu',
    'product.win10.feat2': 'Integrated Cortana',
    'product.win10.feat3': 'Microsoft Edge',
    'product.win10.feat4': 'Dedicated Cloud Environment',
    'product.win10.name': 'Windows 10',
    'product.win10.version': 'Cloud Server Base',
    'product.win11.desc': 'The latest generation of Windows. With integrated AI features to maximize your profits and efficiency.',
    'product.win11.feat1': 'New centered design',
    'product.win11.feat2': 'Integrated widgets',
    'product.win11.feat3': 'Superior performance',
    'product.win11.feat4': 'Copilot AI Pre-installed',
    'product.win11.name': 'Windows 11',
    'product.win11.version': 'NextGen AI Core',
    'product.win7.desc': 'The classic Windows 7 experience, cloud-optimized. Stability and performance for your daily operations.',
    'product.win7.feat1': 'Aero Glass Interface',
    'product.win7.feat2': 'Fast navigation',
    'product.win7.feat3': 'Legacy app support',
    'product.win7.feat4': 'Advanced security',
    'product.win7.name': 'Windows 7',
    'product.win7.version': 'Professional Edition',
    'product.win8.desc': 'Modern design with dynamic tiles. Windows 8 Enterprise offers powerful management tools for your team.',
    'product.win8.feat1': 'Dynamic start screen',
    'product.win8.feat2': 'Touch optimized',
    'product.win8.feat3': 'Enhanced multitasking',
    'product.win8.feat4': 'Official ISO included',
    'product.win8.name': 'Windows 8',
    'product.win8.version': 'Enterprise V2',
    'products.activation': 'Activation',
    'products.active_badge': 'Active',
    'products.available_now': 'Available for immediate deployment',
    'products.back_to_list': 'Back to Products',
    'products.btn_buy': 'Buy',
    'products.buy_success': 'acquired successfully!',
    'products.cloud_space': 'Cloud Space',
    'products.daily': 'Daily Yield',
    'products.daily_income': 'Daily Income',
    'products.duration': 'Duration',
    'products.expiration': 'Expiration',
    'products.my_purchases': 'My Purchases',
    'products.not_found': 'Product not found',
    'products.os_version': 'OS Version',
    'products.overview': 'Overview',
    'products.price': 'Price',
    'products.product_id': 'Product ID',
    'products.secure_payment': 'Secure payment processed through regional gateway.',
    'products.specs': 'Specifications',
    'products.sub': 'High performance Microsoft licenses.',
    'products.tech_support_24h': 'Technical support available 24h.',
    'products.title': 'Products Cloud',
    'products.total_price': 'Final Price',
    'profile.about': 'About Microsoft Exchange',
    'profile.auth': 'Authenticate Account',
    'profile.balance': 'Total Balance',
    'profile.bank_info': 'Bank Information',
    'profile.bank_link': 'Bank Linking',
    'profile.coupons': 'Redeem Coupons',
    'profile.crypto_digital': 'Digital Crypto',
    'profile.history': 'General History',
    'profile.logout': 'Logout',
    'profile.moeda_local': 'Local Currency',
    'profile.operations': 'Start Operations',
    'profile.recharge': 'Recharge',
    'profile.recharge_usdt': 'USDT Recharge',
    'profile.settings': 'Settings',
    'profile.team': 'My Team',
    'profile.title': 'User Profile',
    'profile.total_withdrawn': 'Total Withdrawn',
    'profile.user_cloud': 'Microsoft Exchange User',
    'profile.withdraw': 'Withdraw',
    'recharge.amount': 'Recharge Amount',
    'recharge.amount_requested': 'Amount to Transfer',
    'recharge.bank_dest': 'Destination Bank',
    'recharge.beneficiary': 'Official Beneficiary',
    'recharge.btn_confirm': 'Confirm Recharge',
    'recharge.btn_confirm_deposit': 'Confirm Payment',
    'recharge.btn_finish': 'Finish Recharge',
    'recharge.confirm_title': 'Finalize Deposit',
    'recharge.copy_toast': 'Copied to clipboard!',
    'recharge.deposit_value': 'Deposit Value',
    'recharge.disclaimer': 'By clicking finish, you declare that you are aware that you must perform the transfer via your bank app.',
    'recharge.history_title': 'Recharge history',
    'recharge.iban_deposit': 'IBAN for Deposit',
    'recharge.iban_payment': 'Payment IBAN',
    'recharge.manual_amount': 'Enter Manual Amount',
    'recharge.max_error': 'Maximum recharge amount is 1,000,000 Kz',
    'recharge.method': 'Recharge Method',
    'recharge.min_error': 'Minimum recharge amount is 3,000 Kz',
    'recharge.process_info': 'Usually between 5 to 60 minutes after confirmation.',
    'recharge.process_time': 'Processing Time',
    'recharge.processing': 'Smart Processing Active',
    'recharge.proof_label': 'Attach Receipt',
    'recharge.security_badge': 'Microsoft Exchange Certified Security',
    'recharge.select_bank_prompt': 'Please select a bank to recharge',
    'recharge.selected_bank': 'Selected Bank',
    'recharge.step_amount': 'Recharge Balance',
    'recharge.step_bank': 'Select Bank',
    'recharge.step_details': 'Deposit Details',
    'recharge.suggested_amount': 'Suggested',
    'recharge.title': 'Recharge Account',
    'recharge.upload_btn': 'Click to attach file',
    'settings.active_status': 'Status: Active',
    'settings.authenticate': 'Authenticate account',
    'settings.change_password': 'Change password',
    'settings.fixed_label': 'Fixed',
    'settings.help_title': 'Exchange Help',
    'settings.hero_sub': 'Manage your security details, official verification, and Microsoft Exchange network connections.',
    'settings.identity_confirm': 'Institutional identity confirmation',
    'settings.invite_code': 'Invite code',
    'settings.language': 'Language',
    'settings.logout': 'Logout Session',
    'settings.lost_access': 'Lost access?',
    'settings.lost_access_sub': 'Recover your account using the official Microsoft verification process.',
    'settings.network_info': 'Network Info',
    'settings.phone': 'Linked phone',
    'settings.recovery_btn': 'Start Recovery',
    'settings.security_personalization': 'Security & Personalization',
    'settings.support_btn': 'Talk to Support',
    'settings.support_tech': 'Technical support',
    'settings.support_tech_sub': 'Contact our specialized cloud infrastructure team.',
    'settings.title': 'Account Settings',
    'settings.update_credentials': 'Update your access credentials',
    'social.amount_label': 'Total Withdrawal Value (Kz)',
    'social.bonus_info': 'Publish your proof and win bonuses from 100 Kz up to 9,999 Kz.',
    'social.empty_proofs': 'Be the first to share your success and inspire the community!',
    'social.formats': 'Supported formats: JPG, PNG',
    'social.guarantee': 'Microsoft Exchange Guaranteed Payments',
    'social.help_others': 'Help other users and earn visibility bonuses.',
    'social.history_info': 'Verified Payment History',
    'social.message_label': 'Your Message',
    'social.message_placeholder': 'Write a comment...',
    'social.photo_label': 'Proof Photo',
    'social.proof1_comment': 'Successfully received! Microsoft Exchange really pays.',
    'social.proof2_comment': 'Fast withdrawal via IBAN. I recommend it to everyone!',
    'social.proof_title': 'Social Proof',
    'social.received': 'Received',
    'social.received_value': 'Received Amount',
    'social.see_proofs': 'See real payment proofs from our Microsoft Exchange users.',
    'social.send_btn': 'Send Official Proof',
    'social.send_proof': 'Send Receipt',
    'social.share_sub': 'Send your withdrawal proof to motivate the community.',
    'social.share_success': 'Share your success!',
    'social.title': 'Social Proof',
    'social.transparency_wall': 'Transparency Wall',
    'social.upload_btn': 'Upload proof image',
    'social.your_comment': 'Your Comment',
    'support.encrypted_ticket': 'Encrypted Support Ticket',
    'support.feedback_desc': 'Report bugs, suggest improvements, or ask for technical help directly from our developers.',
    'support.feedback_question': 'How can we improve?',
    'support.feedback_title': 'Technical Feedback',
    'support.header': 'Microsoft Support',
    'support.hero_title': 'How can we help?',
    'support.manager_desc': 'VIP support for team leaders.',
    'support.manager_title': 'Dedicated Manager (Community)',
    'support.msg_placeholder': 'Describe your problem or suggestion here...',
    'support.search_placeholder': 'Type here to search official help...',
    'support.security_desc': 'All support interactions are encrypted and verified by Microsoft.',
    'support.security_title': 'Your security is our priority',
    'support.send_msg': 'Send Message',
    'support.tech_desc': 'We are here to help 24 hours a day.',
    'support.tech_title': 'Talk to Technical Support',
    'support.whatsapp_desc': 'Official community of investors and bonuses.',
    'support.whatsapp_title': 'Join WhatsApp Group',
    'support.your_msg': 'Your Message',
    'team.active': 'Active',
    'team.empty': 'Waiting for new members',
    'team.header': 'My Team',
    'team.inactive': 'Inactive',
    'team.level1': '1st Level',
    'team.level2': '2nd Level',
    'team.level3': '3rd Level',
    'team.member_since': 'Member since',
    'team.search_placeholder': 'Search member...',
    'team.stats_com': 'Team Commissions',
    'team.stats_total': 'Total Members',
    'withdraw.amount': 'Withdrawal Amount',
    'withdraw.amount_placeholder': 'Enter amount (Min. 3,000 Kz)',
    'withdraw.bank_acc': 'Bank Account',
    'withdraw.bank_required': 'Please register a bank account first.',
    'withdraw.btn_request': 'Request',
    'withdraw.empty': 'You haven\'t made any withdrawal requests on this account yet.',
    'withdraw.est_payment': 'Estimated Payment',
    'withdraw.gross_amount': 'Gross Amount',
    'withdraw.history_desc': 'View the status and details of your withdrawal requests.',
    'withdraw.history_title': 'Withdrawal Record',
    'withdraw.info1': 'Processing in 5-60 minutes after approval.',
    'withdraw.info2': '14% fee for Microsoft Exchange ecosystem maintenance.',
    'withdraw.info_title': 'Withdrawal Information',
    'withdraw.insufficient': 'Insufficient balance.',
    'withdraw.min_amount': 'The minimum withdrawal amount is 3,000 Kz',
    'withdraw.net_amount': 'Net Amount',
    'withdraw.password': 'Login Password',
    'withdraw.req_date': 'Request Date',
    'withdraw.security_pass_placeholder': 'Enter login password',
    'withdraw.tax': 'Service Fee (14%)',
    'withdraw.time_error': 'Withdrawals only available from 10:00 to 16:00.',
    'withdraw.title': 'Request Withdrawal',
    'withdraw.total_net': 'Net Total',
    'withdraw.until': 'Until',
    'withdraw.verify_required': 'Your account must be verified (ID approved) to make withdrawals.',
  },
  fr: {
    'about.commitments': 'Nos Engagements',
    'about.header': 'À propos de Microsoft Exchange',
    'about.hero_sub': 'Découvrez comment la technologie Microsoft permet aux individus du monde entier de créer l\'avenir qu\'ils souhaitent.',
    'about.hero_title': 'Nous croyons en ce qui est possible.',
    'about.local_p1': 'Les utilisateurs en Angola peuvent désormais accéder à nos services et rejoindre l\'écosystème officiel de notre entreprise.',
    'about.local_title': 'Plateforme et écosystème locaux',
    'about.mission_desc': 'Donner à chaque personne et à chaque organisation sur la planète les moyens d\'accomplir plus grâce à la technologie.',
    'about.mission_title': 'Notre Mission',
    'about.quote': '"Notre voyage consiste à construire de la technologie pour que d\'autres puissent construire plus de technologie."',
    'about.rights': '© 2026 Microsoft Exchange. Tous droits réservés.',
    'about.stat_countries': 'Pays',
    'about.stat_foundation': 'Fondation',
    'about.stat_licenses': 'Licences',
    'about.stat_people': 'Personnes',
    'about.vision_label': 'Aperçu',
    'about.vision_p1': 'Microsoft Exchange est une force motrice de l\'innovation technologique mondiale. Nous sommes passés d\'une société de logiciels à un leader des services cloud intelligents.',
    'about.vision_p2': 'Grâce à des avancées pionnières en IA, nous proposons les outils nécessaires aux organisations pour transformer leur productivité.',
    'about.vision_title': 'Mener la transformation numérique mondiale.',
    'auth.btn_register': 'S\'inscrire',
    'auth.captcha_error_empty': 'Veuillez remplir la vérification Captcha',
    'auth.captcha_error_wrong': 'Code Captcha incorrect. Réessayez.',
    'auth.captcha_label': 'Validation Captcha',
    'auth.captcha_placeholder': 'Code captcha',
    'auth.create_one': 'Créez-en un !',
    'auth.enter_password': 'Saisir le mot de passe',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.has_account': 'Vous avez déjà un compte ?',
    'auth.invite_code': 'Code d\'invitation',
    'auth.invite_error_empty': 'Veuillez saisir le code d\'invitation',
    'auth.invite_placeholder': 'Saisir le code (INV-XXXXX)',
    'auth.login': 'Se connecter',
    'auth.no_account': 'Pas de compte ?',
    'auth.password_error_complexity': 'Le mot de passe doit contenir des lettres et des chiffres',
    'auth.password_error_empty': 'Veuillez saisir le mot de passe',
    'auth.password_error_length': 'Le mot de passe doit avoir 8 caractères ou plus',
    'auth.password_error_simple': 'Mot de passe trop simple. Veuillez choisir un mot de passe plus sûr.',
    'auth.password_error_wrong': 'Mot de passe de connexion incorrect.',
    'auth.password_label': 'Mot de passe',
    'auth.password_placeholder': 'Saisir le mot de passe',
    'auth.password_signup_placeholder': 'Au moins 8 caractères',
    'auth.phone_error_empty': 'Veuillez saisir le numéro',
    'auth.phone_error_format': 'Numéro invalide pour le format local',
    'auth.phone_error_invalid': 'Ce numéro de téléphone semble invalide',
    'auth.phone_error_length': 'Le numéro doit avoir 9 chiffres',
    'auth.phone_label': 'Numéro de téléphone',
    'auth.phone_placeholder': 'Saisir le numéro (9XXXXXXXX)',
    'auth.signup': 'Inscription',
    'auth.signup_success': 'Compte créé avec succès !',
    'auth.signup_title': 'Créer un compte',
    'auth.welcome_back': 'Bon retour !',
    'auth.invite_error_length': 'Le code d\'invitation doit avoir 10 chiffres numériques.',
    'bank.add_new': '+ Ajouter un nouveau mode de paiement',
    'bank.bind': 'Lier la Banque',
    'bank.desc': 'Assurez-vous que les données correspondent à votre pièce d\'identité pour éviter les retards de retrait.',
    'bank.holder': 'Nom du Titulaire',
    'bank.holder_placeholder': 'Ex: Jean Dupont',
    'bank.iban': 'IBAN Angolais',
    'bank.info_desc': 'Gérez comment vous recevez des fonds et vérifiez le statut de vérification de vos comptes.',
    'bank.info_title': 'Paiement et facturation',
    'bank.name': 'Banque',
    'bank.remove': 'Supprimer ce mode de paiement',
    'bank.save_btn': 'Enregistrer les Données',
    'bank.security': 'Sécurité et conformité',
    'bank.security_desc': 'Les informations de votre compte bancaire sont stockées en toute sécurité et cryptées. Microsoft Exchange suit les normes mondiales de conformité financière pour garantir que vos transactions sont toujours protégées.',
    'bank.select': 'Sélectionner l\'Institution',
    'bank.title': 'Compte Bancaire',
    'bank.verified': 'Vérifié',
    'common.back': 'Retour',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.copied': 'Copié',
    'common.copy': 'Copier',
    'common.error': 'Erreur',
    'common.loading': 'Chargement...',
    'common.next': 'Suivant',
    'common.prev': 'Précédent',
    'common.save': 'Enregistrer',
    'common.send': 'Envoyer',
    'common.status': 'Statut',
    'common.success': 'Succès',
    'common.verified': 'Vérifié',
    'common.warning': 'Avertissement',
    'coupons.btn': 'Utiliser Maintenant',
    'coupons.error_invalid': 'Veuillez saisir un code de coupon valide.',
    'coupons.hero_sub': 'Saisissez le code promo fourni par votre gestionnaire ou dans les groupes officiels.',
    'coupons.hero_title': 'Activer le Bonus',
    'coupons.label': 'Code du Coupon',
    'coupons.placeholder': 'Saisissez le code',
    'coupons.title': 'Utiliser un Coupon',
    'faq.feedback_thanks': 'Merci pour votre commentaire !',
    'faq.feedback_useful': 'Ces informations ont-elles été utiles ?',
    'faq.header': 'Questions Fréquentes',
    'faq.hero_sub': 'Trouvez des guides et des réponses sur la plateforme.',
    'faq.hero_title': 'Aide technique',
    'faq.no': 'Non',
    'faq.q1': 'Comment recharger mon compte ?',
    'faq.q2': 'Comment retirer mes gains ?',
    'faq.q3': 'Comment accomplir la tâche quotidienne ?',
    'faq.q4': 'Quelle est la durée des produits ?',
    'faq.q5': 'Comment fonctionne la plateforme ?',
    'faq.q6': 'Comment utiliser le support ?',
    'faq.q7': 'Gains par équipe ?',
    'faq.yes': 'Oui',
    'history.activated_at': 'Activé le',
    'history.backup_iso': 'MB',
    'history.completed': 'Terminé',
    'history.empty': 'Aucune licence active trouvée.',
    'history.empty_cat': 'Aucune activité enregistrée dans cette catégorie.',
    'history.failed': 'Échoué',
    'history.filter_all': 'Tout Afficher (Aperçu)',
    'history.filter_cat': 'Filtrer la Catégorie',
    'history.filter_coupon': 'Échange de Coupons',
    'history.filter_income': 'Revenus Quotidiens',
    'history.filter_recharge': 'Recharges de Solde',
    'history.filter_team': 'Commissions & Bonus d\'Équipe',
    'history.filter_withdraw': 'Retraits',
    'history.filtered': 'Filtré',
    'history.full_list': 'Liste Complète',
    'history.general_desc': 'Registre complet de vos opérations financières dans le cloud.',
    'history.general_title': 'Historique des Activités',
    'history.investment': 'Investissement',
    'history.license_id': 'ID de Licence',
    'history.loading': 'Synchronisation avec les serveurs Microsoft...',
    'history.manage_server': 'Télécharger le Setup',
    'history.pending': 'En Revue',
    'history.real_time': 'Temps Réel',
    'history.remaining': 'Durée Restante',
    'history.status': 'Statut',
    'history.status_active': 'Actif et Rentable',
    'history.status_expired': 'Expiré',
    'history.syncing': 'Synchronisation des Activités...',
    'history.title': 'Mes Licences',
    'home.announcement.content1': 'Votre voyage vers l\'indépendance financière commence ici. Microsoft Exchange Technologie offre l\'infrastructure cloud la plus sécurisée e rentable du marché angolais.',
    'home.announcement.content2': 'Gagnez des bonus sur 3 niveaux en invitant vos amis et votre famille dans notre communauté.',
    'home.announcement.content3': 'Rejoignez notre WhatsApp pour les preuves de paiement et un support technique prioritaire.',
    'home.announcement.title1': 'Bienvenue sur Microsoft Exchange Angola',
    'home.announcement.title2': 'Système d\'invitation et gains d\'équipe',
    'home.announcement.title3': 'Communauté Microsoft officielle',
    'home.community_btn': 'Rejoindre la communauté',
    'home.doubts': 'Des doutes?',
    'home.hero_sub': 'Commencez votre voyage avec l\'infrastructure la plus robuste du marché.',
    'home.marquee': 'Bienvenue sur Microsoft Exchange Angola ! Profitez de nos offres de serveurs exclusives pour booster votre rendement quotidien. Restez à l\'écoute de nos mises à jour officielles.',
    'home.news': 'Nouvelles',
    'home.secure': 'Sécurisé',
    'home.servers': 'Serveurs',
    'home.social_proof': 'Preuves de retrait',
    'home.support_btn': 'Accéder au support',
    'home.support_cta': 'Contactez notre support officiel Microsoft Exchange Partner disponible 24h/24.',
    'home.users': 'Utilisateurs',
    'home.welcome_hero': 'Bienvenue sur Exchange Experience',
    'identity.auth_account': 'Authentifiez votre compte',
    'identity.auth_desc': 'Pour garantir la sécurité des transactions, nous devons valider vos documents officiels.',
    'identity.back': 'Verso de la pièce d\'identité',
    'identity.btn_send': 'Envoyer pour Vérification',
    'identity.front': 'Recto de la pièce d\'identité',
    'identity.full_name': 'Nom Complet (Selon la pièce d\'identité)',
    'identity.id_number': 'Numéro d\'identité (14 caractères)',
    'identity.pgp': 'Protection PGP Active',
    'identity.province': 'Province de Résidence',
    'identity.status_pending': 'Vérification en Cours',
    'identity.status_pending_desc': 'Vos documents ont été reçus et sont en cours d\'analyse. Cela peut prendre jusqu\'à 24h.',
    'identity.status_verified': 'Compte Vérifié',
    'identity.status_verified_desc': 'Votre identité a été authentifiée avec succès par les serveurs Microsoft.',
    'identity.title': 'Vérification d\'Identité',
    'invite.btn_share': 'Partager Maintenant',
    'invite.code_label': 'Code d\'invitation',
    'invite.copy_toast': 'Copié dans le presse-papier !',
    'invite.link_label': 'Lien d\'invitation',
    'invite.partnership': 'Réseau de Partenariat',
    'invite.team_btn': 'Mon Équipe',
    'invite.title': 'Inviter des Amis',
    'invite.toast_share': 'Options de partage ouvertes !',
    'nav.home': 'Accueil',
    'nav.invite': 'Inviter',
    'nav.products': 'Produits',
    'nav.profile': 'Profil',
    'ops.btn_finished': 'Travail terminé',
    'ops.btn_start': 'Démarrer les opérations',
    'ops.collect': 'Collecte des gains',
    'ops.collect_sub': 'Activez vos serveurs pour obtenir des profits quotidiens.',
    'ops.completed': 'Terminé',
    'ops.estimated': 'Rendement estimé',
    'ops.processing': 'Traitement...',
    'ops.synchronized': 'Synchronisé',
    'ops.system_status': 'Statut du système',
    'ops.tasks_left': 'Tâches restantes',
    'ops.title': 'Démarrer les opérations',
    'ops.waiting': 'En attente',
    'password.btn_update': 'Mettre à jour le mot de passe',
    'password.confirm_label': 'Confirmer le nouveau mot de passe',
    'password.confirm_placeholder': 'Répéter le nouveau mot de passe',
    'password.match_error': 'Les nouveaux mots de passe ne correspondent pas !',
    'password.new_label': 'Nouveau mot de passe',
    'password.new_placeholder': '8 caractères minimum',
    'password.old_label': 'Ancien mot de passe',
    'password.old_placeholder': 'Confirmer le mot de passe actuel',
    'password.protection': 'Protection Cryptée',
    'password.recommendation': 'Nous recommandons d\'utiliser des lettres et des chiffres pour plus de sécurité.',
    'password.security': 'Sécurité du Compte',
    'password.success': 'Mot de passe modifié avec succès !',
    'password.title': 'Changer le mot de passe',
    'product.unit.day': 'jour',
    'product.unit.days': 'jours',
    'product.win10.desc': 'La référence de l\'informatique moderne. Version Cloud Server avec haute disponibilité et ressources serveur.',
    'product.win10.feat1': 'Menu Démarrer classique',
    'product.win10.feat2': 'Cortana intégrée',
    'product.win10.feat3': 'Microsoft Edge',
    'product.win10.feat4': 'Environnement Cloud dédié',
    'product.win10.name': 'Windows 10',
    'product.win10.version': 'Cloud Server Base',
    'product.win11.desc': 'La dernière génération de Windows. Avec des fonctionnalités d\'IA intégrées pour maximiser vos profits et votre efficacité.',
    'product.win11.feat1': 'Nouveau design centré',
    'product.win11.feat2': 'Widgets intégrés',
    'product.win11.feat3': 'Performances supérieures',
    'product.win11.feat4': 'Copilot AI pré-installé',
    'product.win11.name': 'Windows 11',
    'product.win11.version': 'NextGen AI Core',
    'product.win7.desc': 'L\'expérience classique de Windows 7, optimisée pour le cloud. Stabilité et performance pour vos opérations quotidiennes.',
    'product.win7.feat1': 'Interface Aero Glass',
    'product.win7.feat2': 'Navigation rapide',
    'product.win7.feat3': 'Support apps héritées',
    'product.win7.feat4': 'Sécurité avancée',
    'product.win7.name': 'Windows 7',
    'product.win7.version': 'Professional Edition',
    'product.win8.desc': 'Design moderne avec tuiles dynamiques. Windows 8 Enterprise offre des outils de gestion puissants.',
    'product.win8.feat1': 'Écran d\'accueil dynamique',
    'product.win8.feat2': 'Optimisé tactile',
    'product.win8.feat3': 'Multitâche amélioré',
    'product.win8.feat4': 'ISO officiel inclus',
    'product.win8.name': 'Windows 8',
    'product.win8.version': 'Enterprise V2',
    'products.activation': 'Activation',
    'products.active_badge': 'Actif',
    'products.available_now': 'Disponible pour un déploiement immédiat',
    'products.back_to_list': 'Retour aux Produits',
    'products.btn_buy': 'Acheter',
    'products.buy_success': 'acquis avec succès !',
    'products.cloud_space': 'Espace Cloud',
    'products.daily': 'Rendement Quotidien',
    'products.daily_income': 'Revenu Quotidien',
    'products.duration': 'Durée',
    'products.expiration': 'Expiration',
    'products.my_purchases': 'Mes Achats',
    'products.not_found': 'Produit non trouvé',
    'products.os_version': 'Version de l\'OS',
    'products.overview': 'Aperçu',
    'products.price': 'Prix',
    'products.product_id': 'ID du Produit',
    'products.secure_payment': 'Paiement sécurisé via passerelle régionale.',
    'products.specs': 'Spécifications',
    'products.sub': 'Licences Microsoft haute performance.',
    'products.tech_support_24h': 'Support technique disponible 24h/24.',
    'products.title': 'Nuage de Produits',
    'products.total_price': 'Prix Final',
    'profile.about': 'À propos de Microsoft Exchange',
    'profile.auth': 'Authentifier le compte',
    'profile.balance': 'Solde Total',
    'profile.bank_info': 'Informations Bancaires',
    'profile.bank_link': 'Liaison Bancaire',
    'profile.coupons': 'Utiliser des Coupons',
    'profile.crypto_digital': 'Crypto Digitale',
    'profile.history': 'Historique Général',
    'profile.logout': 'Déconnexion',
    'profile.moeda_local': 'Monnaie Locale',
    'profile.operations': 'Démarrer les opérations',
    'profile.recharge': 'Recharger',
    'profile.recharge_usdt': 'Recharge USDT',
    'profile.settings': 'Paramètres',
    'profile.team': 'Mon Équipe',
    'profile.title': 'Profil de l\'Utilisateur',
    'profile.user_cloud': 'Utilisateur Microsoft Exchange',
    'profile.withdraw': 'Retirer',
    'recharge.amount': 'Montant de la recharge',
    'recharge.amount_requested': 'Montant à Transférer',
    'recharge.bank_dest': 'Banque de Destination',
    'recharge.beneficiary': 'Bénéficiaire officiel',
    'recharge.btn_confirm': 'Confirmer la recharge',
    'recharge.btn_confirm_deposit': 'Confirmer le Paiement',
    'recharge.btn_finish': 'Terminer la recharge',
    'recharge.confirm_title': 'Finaliser le Dépôt',
    'recharge.copy_toast': 'Copié dans le presse-papier!',
    'recharge.deposit_value': 'Valeur du dépôt',
    'recharge.disclaimer': 'En cliquant sur terminer, vous déclarez être conscient que vous devez effectuer le transfert via votre application bancaire.',
    'recharge.history_title': 'Historique des recharges',
    'recharge.iban_deposit': 'IBAN pour le Dépôt',
    'recharge.iban_payment': 'IBAN de paiement',
    'recharge.manual_amount': 'Saisir le montant manuel',
    'recharge.max_error': 'Le montant maximum de recharge est de 1 000 000 Kz',
    'recharge.method': 'Méthode de recharge',
    'recharge.min_error': 'Le montant minimum de recharge est de 3 000 Kz',
    'recharge.process_info': 'Généralement entre 5 et 60 minutes après confirmation.',
    'recharge.process_time': 'Temps de traitement',
    'recharge.processing': 'Traitement Intelligent Actif',
    'recharge.proof_label': 'Joindre le Reçu',
    'recharge.security_badge': 'Sécurité Certifiée Microsoft Exchange',
    'recharge.select_bank_prompt': 'Veuillez sélectionner une banque pour recharger',
    'recharge.selected_bank': 'Banque sélectionnée',
    'recharge.step_amount': 'Recharger le solde',
    'recharge.step_bank': 'Sélectionner la banque',
    'recharge.step_details': 'Détails du dépôt',
    'recharge.suggested_amount': 'Suggestions',
    'recharge.title': 'Recharger le compte',
    'recharge.upload_btn': 'Cliquez pour joindre le fichier',
    'settings.active_status': 'Statut : Actif',
    'settings.authenticate': 'Authentifier le compte',
    'settings.change_password': 'Changer le mot de passe',
    'settings.fixed_label': 'Fixe',
    'settings.help_title': 'Aide Exchange',
    'settings.hero_sub': 'Gérez vos détails de sécurité, votre vérification officielle et vos connexions réseau Microsoft Exchange.',
    'settings.identity_confirm': 'Confirmation d\'identité institutionnelle',
    'settings.invite_code': 'Code d\'invitation',
    'settings.language': 'Langue',
    'settings.logout': 'Déconnexion',
    'settings.lost_access': 'Accès perdu?',
    'settings.lost_access_sub': 'Récupérez votre compte en utilisant le processus de vérification officiel de Microsoft.',
    'settings.network_info': 'Informations réseau',
    'settings.phone': 'Téléphone lié',
    'settings.recovery_btn': 'Démarrer la récupération',
    'settings.security_personalization': 'Sécurité & Personnalisation',
    'settings.support_btn': 'Parler au support',
    'settings.support_tech': 'Support technique',
    'settings.support_tech_sub': 'Contactez notre équipe spécialisée en infrastructure cloud.',
    'settings.title': 'Paramètres du compte',
    'settings.update_credentials': 'Mettez à jour vos identifiants d\'accès',
    'social.amount_label': 'Valeur totale du retrait (Kz)',
    'social.bonus_info': 'Publiez votre preuve et gagnez des bonus de 100 Kz à 9 999 Kz.',
    'social.empty_proofs': 'Soyez le premier à partager votre succès et à inspirer la communauté !',
    'social.formats': 'Formats supportés : JPG, PNG',
    'social.guarantee': 'Paiements garantis Microsoft Exchange',
    'social.help_others': 'Aidez d\'autres utilisateurs et gagnez des bonus de visibilité.',
    'social.history_info': 'Historique des paiements vérifiés',
    'social.message_label': 'Votre Message',
    'social.message_placeholder': 'Écrire un commentaire...',
    'social.photo_label': 'Photo de la preuve',
    'social.proof1_comment': 'Reçu avec succès ! Microsoft Exchange paie vraiment.',
    'social.proof2_comment': 'Retrait rapide via IBAN. Je le recommande à tout le monde !',
    'social.proof_title': 'Preuve Sociale',
    'social.received': 'Reçu',
    'social.received_value': 'Montant Reçu',
    'social.see_proofs': 'Voir les preuves de paiement réelles de nos utilisateurs Microsoft Exchange.',
    'social.send_btn': 'Envoyer la preuve officielle',
    'social.send_proof': 'Envoyer le Reçu',
    'social.share_sub': 'Envoyez votre preuve de retrait pour motiver la communauté.',
    'social.share_success': 'Partagez votre succès !',
    'social.title': 'Preuves Sociales',
    'social.transparency_wall': 'Mur de Transparence',
    'social.upload_btn': 'Charger l\'image de preuve',
    'social.your_comment': 'Votre Commentaire',
    'support.encrypted_ticket': 'Ticket de Support Crypté',
    'support.feedback_desc': 'Signalez des bugs, suggérez des améliorations ou demandez une aide technique directement à nos développeurs.',
    'support.feedback_question': 'Comment pouvons-nous nous améliorer ?',
    'support.feedback_title': 'Rétroaction Technique',
    'support.header': 'Support Microsoft',
    'support.hero_title': 'Comment pouvons-nous vous aider ?',
    'support.manager_desc': 'Support VIP pour les chefs d\'équipe.',
    'support.manager_title': 'Gestionnaire dédié (Communauté)',
    'support.msg_placeholder': 'Décrivez votre problème ou suggestion ici...',
    'support.search_placeholder': 'Tapez ici pour rechercher l\'aide officielle...',
    'support.security_desc': 'Toutes les interactions de support sont cryptées et vérifiées par Microsoft.',
    'support.security_title': 'Votre sécurité est notre priorité',
    'support.send_msg': 'Envoyer le Message',
    'support.tech_desc': 'Nous sommes là pour vous aider 24h/24.',
    'support.tech_title': 'Parler au support technique',
    'support.whatsapp_desc': 'Communauté officielle des investisseurs et bonus.',
    'support.whatsapp_title': 'Rejoindre le groupe WhatsApp',
    'support.your_msg': 'Votre Message',
    'team.active': 'Actif',
    'team.empty': 'En attente de nouveaux membres',
    'team.header': 'Mon Équipe',
    'team.inactive': 'Inactif',
    'team.level1': '1er Niveau',
    'team.level2': '2e Niveau',
    'team.level3': '3e Niveau',
    'team.member_since': 'Membre depuis',
    'team.search_placeholder': 'Rechercher un membre...',
    'team.stats_com': 'Commissions d\'Équipe',
    'team.stats_total': 'Total des Membres',
    'withdraw.amount': 'Montant du Retrait',
    'withdraw.amount_placeholder': 'Entrer le montant (Min. 3 000 Kz)',
    'withdraw.bank_acc': 'Compte Bancaire',
    'withdraw.bank_required': 'Veuillez d\'abord enregistrer un compte bancaire.',
    'withdraw.btn_request': 'Demander',
    'withdraw.empty': 'Vous n\'avez pas encore effectué de demandes de retrait sur ce compte.',
    'withdraw.est_payment': 'Paiement Estimé',
    'withdraw.gross_amount': 'Montant Brut',
    'withdraw.history_desc': 'Affichez le statut et les détails de vos demandes de retrait.',
    'withdraw.history_title': 'Registre de retrait',
    'withdraw.info1': 'Traitement en 5 à 60 minutes après approbation.',
    'withdraw.info2': 'Frais de 14% pour la maintenance de l\'écosystème Microsoft Exchange.',
    'withdraw.info_title': 'Informations sur le Retrait',
    'withdraw.insufficient': 'Solde insuffisant.',
    'withdraw.min_amount': 'Le montant minimum de retrait est de 3 000 Kz',
    'withdraw.net_amount': 'Montant Net',
    'withdraw.password': 'Mot de Passe de Connexion',
    'withdraw.req_date': 'Date de Demande',
    'withdraw.security_pass_placeholder': 'Saisir le mot de passe de connexion',
    'withdraw.tax': 'Frais de Service (14%)',
    'withdraw.time_error': 'Retraits disponibles uniquement de 10h00 à 16h00.',
    'withdraw.title': 'Demander un Retrait',
    'withdraw.total_net': 'Total Net',
    'withdraw.until': 'Jusqu\'à',
    'withdraw.verify_required': 'Votre compte doit être vérifié (ID approuvé) pour effectuer des retraits.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Inicializar com o idioma salvo ou padrão 'pt'
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language') as Language;
    return (saved === 'pt' || saved === 'en' || saved === 'fr') ? saved : 'pt';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
