import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.products': 'Produtos',
    'nav.invite': 'Convidar',
    'nav.profile': 'Perfil',

    // Common
    'common.copy': 'Copiar',
    'common.copied': 'Copiado',
    'common.confirm': 'Confirmar',
    'common.cancel': 'Cancelar',
    'common.next': 'Próximo',
    'common.prev': 'Anterior',
    'common.back': 'Voltar',
    'common.close': 'Fechar',
    'common.send': 'Enviar',
    'common.save': 'Guardar',
    'common.loading': 'Carregando...',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.warning': 'Aviso',
    'common.status': 'Estado',
    'common.verified': 'Verificada',

    // Home Page
    'home.welcome_hero': 'Bem-vindo à Exchange Experience',
    'home.hero_sub': 'Comece sua jornada com a infraestrutura mais robusta do mercado.',
    'home.users': 'Usuários',
    'home.secure': 'Seguro',
    'home.servers': 'Servidores',
    'home.news': 'Notícias',
    'home.social_proof': 'Provas de Saque',
    'home.doubts': 'Dúvidas?',
    'home.support_cta': 'Fale com o nosso suporte oficial Microsoft Partner disponível 24 horas.',
    'home.support_btn': 'Acessar Suporte',
    'home.marquee': 'Bem-vindo à Microsoft Exchange Angola! Aproveite nossas ofertas exclusivas de servidores para impulsionar seu rendimento diário. Fique atento às nossas atualizações oficiais.',
    'home.announcement.title1': 'Seja bem-vindo à Microsoft Exchange Angola',
    'home.announcement.content1': 'Sua jornada rumo à independência financeira começa aqui. A Microsoft Exchange Tecnologia oferece a infraestrutura de nuvem mais segura e rentável do mercado angolano.',
    'home.announcement.title2': 'Sistema de Convites e Ganhos em Equipe',
    'home.announcement.content2': 'Ganhe bônus em 3 níveis convidando amigos e familiares para a nossa comunidade.',
    'home.announcement.title3': 'Comunidade Oficial Microsoft',
    'home.announcement.content3': 'Junte-se ao nosso WhatsApp para provas de pagamento e suporte técnico prioritário.',
    'home.community_btn': 'Entrar na Comunidade',

    // Profile Page
    'profile.title': 'Perfil do Utilizador',
    'profile.balance': 'Saldo Total',
    'profile.recharge': 'Recarregar',
    'profile.withdraw': 'Retirar',
    'profile.total_withdrawn': 'Total Retirada',
    'profile.operations': 'Iniciar Operações',
    'profile.team': 'Minha Equipe',
    'profile.history': 'Histórico Geral',
    'profile.auth': 'Autenticar Conta',
    'profile.bank_link': 'Vinculação Bancária',
    'profile.bank_info': 'Informações Bancárias',
    'profile.coupons': 'Resgatar Cupons',
    'profile.about': 'Sobre Microsoft Exchange',
    'profile.settings': 'Configurações',
    'profile.logout': 'Sair da Conta',
    'profile.recharge_usdt': 'Recarga USDT',
    'profile.user_cloud': 'Utilizador Microsoft Exchange',
    'profile.moeda_local': 'Moeda Local',
    'profile.crypto_digital': 'Crypto Digital',

    // Settings Page
    'settings.title': 'Configurações de Conta',
    'settings.hero_sub': 'Gerencie seus detalhes de segurança, verificação oficial e conexões de rede Microsoft Exchange.',
    'settings.language': 'Idioma',
    'settings.change_password': 'Alterar senha',
    'settings.authenticate': 'Autenticar conta',
    'settings.phone': 'Telefone vinculado',
    'settings.invite_code': 'Código de convite',
    'settings.security_personalization': 'Segurança e Personalização',
    'settings.network_info': 'Informações de Redes',
    'settings.help_title': 'Ajuda Exchange',
    'settings.lost_access': 'Perdeu o acesso?',
    'settings.lost_access_sub': 'Recupere sua conta usando o processo oficial de verificação Microsoft.',
    'settings.support_tech': 'Suporte técnico',
    'settings.support_tech_sub': 'Contate nossa equipa especializada em infraestrutura de nuvem.',
    'settings.recovery_btn': 'Iniciar Recuperação',
    'settings.support_btn': 'Falar com Suporte',
    'settings.logout': 'Encerrar Sessão',
    'settings.active_status': 'Estado: Ativo',
    'settings.update_credentials': 'Atualize suas credenciais de acesso',
    'settings.identity_confirm': 'Confirmação de identidade institucional',
    'settings.fixed_label': 'Fixo',

    // Operations Page
    'ops.title': 'Iniciar Operações',
    'ops.collect': 'Coleta de Rendimentos',
    'ops.collect_sub': 'Ative seus servidores para obter lucros diários.',
    'ops.system_status': 'Status do Sistema',
    'ops.processing': 'Processando...',
    'ops.completed': 'Concluído',
    'ops.waiting': 'Aguardando',
    'ops.synchronized': 'Sincronizado',
    'ops.estimated': 'Rendimento Estimado',
    'ops.tasks_left': 'Tarefas Restantes',
    'ops.btn_start': 'Iniciar Operações',
    'ops.btn_finished': 'Trabalho Concluído',

    // Withdraw Page
    'common.fill_fields': 'Por favor, preencha todos os campos obrigatórios.',
    'withdraw.title': 'Solicitar Retirada',
    'withdraw.amount': 'Valor da Retirada',
    'withdraw.amount_placeholder': 'Introduzir valor (Mín. 3.000 Kz)',
    'withdraw.min_error': 'O valor mínimo de retirada é de 3.000 Kz',
    'withdraw.bank_acc': 'Conta Bancária',
    'withdraw.bank_placeholder': 'Selecionar conta vinculada',
    'withdraw.security_pass': 'Senha de Segurança',
    'withdraw.security_pass_placeholder': 'Introduzir senha de login',
    'withdraw.tax': 'Taxa de Serviço',
    'withdraw.net_total': 'Total Liquido',
    'withdraw.info_title': 'Informações de Retirada',
    'withdraw.info1': 'Processamento em 5-60 minutos após aprovação.',
    'withdraw.info2': 'Taxa de 14% para manutenção do ecossistema Microsoft Exchange.',
    'withdraw.btn_confirm': 'Confirmar Retirada',

    // Recharge Page
    'recharge.title': 'Recarregar Conta',
    'recharge.method': 'Método de Recarga',
    'recharge.amount': 'Valor da Recarga',
    'recharge.btn_confirm': 'Confirmar Recarga',

    // Products Page
    'products.title': 'Nuvem de Produtos',
    'products.sub': 'Licenças Microsoft de alta performance.',
    'products.price': 'Preço',
    'products.daily': 'Renda Diária',
    'products.duration': 'Duração',
    'products.btn_buy': 'Comprar',
    'products.my_purchases': 'Minhas Compras',

    // Recharge Page
    'recharge.suggested_amount': 'Sugestões',
    'recharge.manual_amount': 'Introduzir Valor Manual',
    'recharge.min_error': 'O valor mínimo de recarga é de 3.000 Kz',
    'recharge.max_error': 'O valor máximo de recarga é de 1.000.000 Kz',
    'recharge.select_bank_prompt': 'Por favor selecione um banco para carregar',
    'recharge.step_amount': 'Recarregar Saldo',
    'recharge.step_bank': 'Selecionar Banco',
    'recharge.step_details': 'Detalhes de Depósito',
    'recharge.selected_bank': 'Banco Selecionado',
    'recharge.iban_payment': 'IBAN de Pagamento',
    'recharge.beneficiary': 'Favorecido Oficial',
    'recharge.deposit_value': 'Valor do Depósito',
    'recharge.history_title': 'Histórico de recargas',
    'recharge.process_time': 'Tempo de Processamento',
    'recharge.process_info': 'Geralmente entre 5 a 60 minutos após confirmação.',
    'recharge.disclaimer': 'Ao clicar em finalizar, você declara estar ciente de que deve realizar a transferência via aplicativo do seu banco.',
    'recharge.btn_finish': 'Finalizar Recarga',
    'recharge.copy_toast': 'Copiado para a área de transferência!',

    // Social Proof Page
    'social.title': 'Provas Sociais',
    'social.share_success': 'Partilhe o seu sucesso!',
    'social.share_sub': 'Envie o comprovativo do seu saque para motivar a comunidade.',
    'social.photo_label': 'Foto do Comprovativo',
    'social.upload_btn': 'Carregar imagem do comprovativo',
    'social.formats': 'Formatos suportados: JPG, PNG',
    'social.amount_label': 'Valor Total do Saque (Kz)',
    'social.message_label': 'Sua Mensagem',
    'social.message_placeholder': 'Escreva um comentário...',
    'social.send_btn': 'Enviar Prova Oficial',
    'social.history_info': 'Histórico de Pagamentos Verificados',
    'social.bonus_info': 'Publique sua prova e ganhe bônus de 100 Kz até 9.999 Kz.',
    'social.received': 'Recebido',
    'social.guarantee': 'Pagamentos Garantidos Microsoft Exchange',
    'social.proof1_comment': 'Recebido com sucesso! Microsoft Exchange realmente paga.',
    'social.proof2_comment': 'Saque rápido via IBAN. Recomendo a todos!',

    // Password Page
    'password.title': 'Alterar Senha',
    'password.old_label': 'Senha Antiga',
    'password.old_placeholder': 'Confirmar senha atual',
    'password.new_label': 'Nova Senha',
    'password.new_placeholder': 'Mínimo de 8 caracteres',
    'password.confirm_label': 'Confirmar Nova Senha',
    'password.confirm_placeholder': 'Repetir a nova senha',
    'password.match_error': 'As novas senhas não coincidem!',
    'password.success': 'Senha alterada com sucesso!',
    'password.btn_update': 'Atualizar Senha',

    // Auth Pages
    'auth.login': 'Entrar',
    'auth.enter_password': 'Inserir senha',
    'auth.phone_label': 'Número de Telefone',
    'auth.phone_placeholder': 'Introduzir número (9XXXXXXXX)',
    'auth.no_account': 'Não tem uma conta?',
    'auth.create_one': 'Crie uma!',
    'auth.password_label': 'Senha',
    'auth.password_placeholder': 'Introduzir senha',
    'auth.forgot_password': 'Esqueceu a senha?',
    'auth.phone_error_empty': 'Por favor insira o número',
    'auth.phone_error_format': 'Número inválido para o formato local',
    'auth.phone_error_length': 'O número deve possuir 9 dígitos',
    'auth.password_error_empty': 'Por favor introduza a senha',
    'auth.password_error_length': 'A senha deve ter 8 dígitos ou mais',
    'auth.welcome_back': 'Bem-vindo de volta!',
    'auth.signup': 'Cadastro',
    'auth.signup_title': 'Criar conta',
    'auth.invite_code': 'Código de Convite',
    'auth.invite_placeholder': 'Introduzir código (INV-XXXXX)',
    'auth.has_account': 'Já tem uma conta?',
    'auth.captcha_label': 'Validação Captcha',
    'auth.captcha_placeholder': 'Código captcha',
    'auth.password_signup_placeholder': 'Pelo menos 8 caracteres',
    'auth.btn_register': 'Registrar',
    'auth.phone_error_invalid': 'Este número de telefone parece ser inválido',
    'auth.captcha_error_empty': 'Por favor preencha a verificação do CAPTCHA',
    'auth.captcha_error_wrong': 'Código CAPTCHA incorreto. Tente novamente.',
    'auth.invite_error_empty': 'Por favor insira o código de convite',
    'auth.password_error_simple': 'Senha muito simples. Por favor, escolha uma senha mais segura.',
    'auth.password_error_complexity': 'A senha deve conter letras e números',
    'auth.signup_success': 'Conta criada com sucesso!',

    // About Page
    'about.header': 'Sobre Microsoft Exchange',
    'about.hero_title': 'Acreditamos no que é possível.',
    'about.hero_sub': 'Explore como a tecnologia Microsoft está capacitando pessoas em todo o mundo para criarem o futuro que desejam.',
    'about.vision_label': 'Visão Geral',
    'about.vision_title': 'Liderando a transformação digital global.',
    'about.vision_p1': 'A Microsoft Exchange é uma força motriz na inovação tecnológica global. Evoluímos de uma empresa de software para uma líder em serviços de nuvem inteligente.',
    'about.vision_p2': 'Com avanços pioneiros em IA, oferecemos as ferramentas necessárias para que organizações transformem sua produtividade.',
    'about.local_title': 'Plataforma e Ecossistema Local',
    'about.local_p1': 'Utilizadores em Angola podem agora aceder aos nossos serviços e integrar o ecossistema oficial da nossa empresa.',
    'about.commitments': 'Nossos Compromissos',
    'about.mission_title': 'Nossa Missão',
    'about.mission_desc': 'Capacitar cada pessoa e cada organização no planeta a conquistar mais através da tecnologia.',
    'about.stat_foundation': 'Fundação',
    'about.stat_countries': 'Países',
    'about.stat_people': 'Pessoas',
    'about.stat_licenses': 'Licenças',
    'about.quote': '"Nossa jornada é sobre construir tecnologia para que outros possam construir mais tecnologia."',
    'about.rights': '© 2026 Microsoft Exchange. Todos os direitos reservados.',

    // Support Page
    'support.header': 'Suporte Microsoft',
    'support.hero_title': 'Como podemos ajudar?',
    'support.search_placeholder': 'Digite aqui para pesquisar ajuda oficial...',
    'support.whatsapp_title': 'Entre no Grupo de WhatsApp',
    'support.whatsapp_desc': 'Comunidade oficial de investidores e bônus.',
    'support.manager_title': 'Gerente dedicado (Comunidade)',
    'support.manager_desc': 'Suporte VIP para líderes de equipe.',
    'support.tech_title': 'Falar com Atendimento Técnico',
    'support.tech_desc': 'Estamos aqui para ajudar 24 horas por dia.',
    'support.security_title': 'A sua segurança é a nossa prioridade',
    'support.security_desc': 'Todas as interações de suporte são encriptadas e verificadas pela Microsoft.',

    // Identity Page
    'identity.header': 'Verificação de Identidade',
    'identity.hero_title': 'Autenticação',
    'identity.hero_sub': 'Confirme sua identidade para garantir a segurança da sua conta e cumprir com as diretrizes da Microsoft Exchange.',
    'identity.name_label': 'Nome Completo (conforme BI)',
    'identity.name_placeholder': 'Introduzir seu nome completo',
    'identity.id_label': 'Número do BI ou Passaporte',
    'identity.id_placeholder': 'Introduzir o número do documento',
    'identity.province_label': 'Província de Residência',
    'identity.province_placeholder': 'Selecionar sua província',
    'identity.job_label': 'Ocupação Atual',
    'identity.job_placeholder': 'Selecionar sua ocupação',
    'identity.btn_send': 'Enviar para Verificação',
    'identity.info_title': 'Por que isso é necessário?',
    'identity.info_desc': 'A autenticação de identidade nos ajuda a prevenir fraudes e proteger seus ativos financeiros. Seus dados são criptografados.',
    'identity.secure_server': 'Servidor Seguro Microsoft',
    'identity.success': 'Informações enviadas para análise!',
    'identity.error_name': 'Por favor introduza o seu nome completo',
    'identity.error_id': 'Por favor introduza o número do BI ou Passaporte',
    'identity.error_province': 'Por favor selecione a sua província',
    'identity.error_job': 'Por favor selecione a sua ocupação',
    'identity.job_unemployed': 'Desempregado',
    'identity.job_public': 'Funcionário Público',
    'identity.job_private': 'Funcionário Setor Privado',
    'identity.job_merchant': 'Negociante',

    // Team Page
    'team.header': 'Minha Equipa',
    'team.stats_total': 'Membros Totais',
    'team.stats_com': 'Comissões de Equipa',
    'team.level1': '1º Nível',
    'team.level2': '2º Nível',
    'team.level3': '3º Nível',
    'team.search_placeholder': 'Procurar membro...',
    'team.member_since': 'Membro desde',
    'team.active': 'Ativo',
    'team.inactive': 'Inativo',
    'team.empty': 'A aguardar novos membros',

    // FAQ Page
    'faq.header': 'Perguntas Frequentes',
    'faq.hero_title': 'Ajuda técnica',
    'faq.hero_sub': 'Encontre guias e respostas sobre a plataforma.',
    'faq.feedback_useful': 'Estas informações foram úteis?',
    'faq.yes': 'Sim',
    'faq.no': 'Não',
    'faq.feedback_thanks': 'Agradecemos o seu comentário!',
    'faq.q1': 'Como recarregar a minha conta?',
    'faq.q2': 'Como retirar os meus ganhos?',
    'faq.q3': 'Como completar a tarefa diária?',
    'faq.q4': 'Qual é a duração dos produtos?',
    'faq.q5': 'Como funciona a plataforma?',
    'faq.q6': 'Como usar o suporte?',
    'faq.q7': 'Ganhos por equipe?',

    // Products Details
    'products.active_badge': 'Ativo',
    'products.daily_income': 'Renda Diária',
    'products.total_price': 'Preço Final',
    'products.available_now': 'Disponível para implantação imediata',
    'products.os_version': 'Versão do SO',
    'products.cloud_space': 'Espaço em Nuvem',
    'products.product_id': 'ID do Produto',
    'products.overview': 'Visão Geral',
    'products.specs': 'Especificações',
    'products.activation': 'Ativação',
    'products.expiration': 'Expiração',
    'products.secure_payment': 'Pagamento seguro processado via gateway regional.',
    'products.tech_support_24h': 'Suporte técnico disponível 24h.',
    'products.not_found': 'Produto não encontrado',
    'products.back_to_list': 'Voltar para Produtos',
    'products.buy_success': 'adquirida com sucesso!',

    // Specific Product Data (to be used in constants)
    'product.win7.name': 'Windows 7',
    'product.win7.version': 'Professional Edition',
    'product.win7.desc': 'A experiência clássica do Windows 7, otimizada para nuvem. Estabilidade e performance para suas operações diárias.',
    'product.win7.feat1': 'Interface Aero Glass',
    'product.win7.feat2': 'Navegação rápida',
    'product.win7.feat3': 'Suporte a apps legados',
    'product.win7.feat4': 'Segurança avançada',

    'product.win8.name': 'Windows 8',
    'product.win8.version': 'Enterprise V2',
    'product.win8.desc': 'Design moderno com blocos dinâmicos. O Windows 8 Enterprise oferece ferramentas de gestão poderosas para sua equipe.',
    'product.win8.feat1': 'Tela inicial dinâmica',
    'product.win8.feat2': 'Otimizado para toque',
    'product.win8.feat3': 'Multitarefa aprimorada',
    'product.win8.feat4': 'ISO oficial incluso',

    'product.win10.name': 'Windows 10',
    'product.win10.version': 'Cloud Server Base',
    'product.win10.desc': 'O padrão ouro da computação moderna. Versão Cloud Server com alta disponibilidade e recursos de servidor.',
    'product.win10.feat1': 'Menu Iniciar clássico',
    'product.win10.feat2': 'Cortana integrada',
    'product.win10.feat3': 'Microsoft Edge',
    'product.win10.feat4': 'Ambiente Cloud Dedicado',

    'product.win11.name': 'Windows 11',
    'product.win11.version': 'NextGen AI Core',
    'product.win11.desc': 'A última geração do Windows. Com recursos de IA integrados para maximizar seus lucros e eficiência.',
    'product.win11.feat1': 'Novo design centrado',
    'product.win11.feat2': 'Widgets integrados',
    'product.win11.feat3': 'Performance Superior',
    'product.win11.feat4': 'Copilot AI Pre-instalado',

    'product.unit.day': 'dia',
    'product.unit.days': 'dias',

    // Invite Page
    'invite.title': 'Convidar Amigos',
    'invite.team_btn': 'Minha Equipe',
    'invite.partnership': 'Rede de Parceria',
    'invite.link_label': 'Link de Convite',
    'invite.code_label': 'Código de Convite',
    'invite.btn_share': 'Compartilhar Agora',
    'invite.toast_share': 'Opções de compartilhamento abertas!',
    'invite.copy_toast': 'Copiado para a área de transferência!',

    // Coupons
    'coupons.title': 'Resgate de Cupom',
    'coupons.hero_title': 'Ativar Bônus',
    'coupons.hero_sub': 'Insira o código promocional fornecido pelo seu gerente ou nos grupos oficiais.',
    'coupons.label': 'Código do Cupom',
    'coupons.placeholder': 'Introduza o código',
    'coupons.btn': 'Resgatar Agora',
    'coupons.error_invalid': 'Por favor, insira um código de cupom válido.',

    // History / Licenses
    'history.title': 'Minhas Licenças',
    'history.loading': 'Sincronizando com os servidores Microsoft...',
    'history.empty': 'Nenhuma licença ativa encontrada.',
    'history.license_id': 'Licença ID',
    'history.activated_at': 'Ativada em',
    'history.investment': 'Investimento',
    'history.status': 'Status',
    'history.status_active': 'Ativo e Rendendo',
    'history.status_expired': 'Expirado',
    'history.remaining': 'Duração Restante',
    'history.manage_server': 'Fazer Download Setup',
    'history.backup_iso': 'MB',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.invite': 'Invite',
    'nav.profile': 'Profile',

    // Common
    'common.copy': 'Copy',
    'common.copied': 'Copied',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.prev': 'Previous',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.send': 'Send',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.status': 'Status',
    'common.verified': 'Verified',

    // Home Page
    'home.welcome_hero': 'Welcome to Exchange Experience',
    'home.hero_sub': 'Start your journey with the most robust infrastructure on the market.',
    'home.users': 'Users',
    'home.secure': 'Secure',
    'home.servers': 'Servers',
    'home.news': 'News',
    'home.social_proof': 'Withdrawal Proofs',
    'home.doubts': 'Any Doubts?',
    'home.support_cta': 'Talk to our official Microsoft Partner support available 24 hours.',
    'home.support_btn': 'Access Support',
    'home.marquee': 'Welcome to Microsoft Exchange Angola! Enjoy our exclusive server offers to boost your daily yield. Stay tuned for our official updates.',
    'home.announcement.title1': 'Welcome to Microsoft Exchange Angola',
    'home.announcement.content1': 'Your journey to financial independence starts here. Microsoft Exchange Technology offers the most secure and profitable cloud infrastructure.',
    'home.announcement.title2': 'Invite System and Team Earnings',
    'home.announcement.content2': 'Earn bonuses on 3 levels by inviting friends and family to our community.',
    'home.announcement.title3': 'Official Microsoft Community',
    'home.announcement.content3': 'Join our WhatsApp for proof of payment and priority technical support.',
    'home.community_btn': 'Join Community',

    // Profile Page
    'profile.title': 'User Profile',
    'profile.balance': 'Total Balance',
    'profile.recharge': 'Recharge',
    'profile.withdraw': 'Withdraw',
    'profile.operations': 'Start Operations',
    'profile.team': 'My Team',
    'profile.history': 'General History',
    'profile.auth': 'Authenticate Account',
    'profile.bank_link': 'Bank Linking',
    'profile.bank_info': 'Bank Information',
    'profile.coupons': 'Redeem Coupons',
    'profile.about': 'About Microsoft Exchange',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.recharge_usdt': 'USDT Recharge',
    'profile.user_cloud': 'Microsoft Exchange User',
    'profile.moeda_local': 'Local Currency',
    'profile.crypto_digital': 'Digital Crypto',

    // Settings Page
    'settings.title': 'Account Settings',
    'settings.hero_sub': 'Manage your security details, official verification, and Microsoft Exchange network connections.',
    'settings.language': 'Language',
    'settings.change_password': 'Change password',
    'settings.authenticate': 'Authenticate account',
    'settings.phone': 'Linked phone',
    'settings.invite_code': 'Invite code',
    'settings.security_personalization': 'Security & Personalization',
    'settings.network_info': 'Network Info',
    'settings.help_title': 'Exchange Help',
    'settings.lost_access': 'Lost access?',
    'settings.lost_access_sub': 'Recover your account using the official Microsoft verification process.',
    'settings.support_tech': 'Technical support',
    'settings.support_tech_sub': 'Contact our specialized cloud infrastructure team.',
    'settings.recovery_btn': 'Start Recovery',
    'settings.support_btn': 'Talk to Support',
    'settings.logout': 'Logout Session',
    'settings.active_status': 'Status: Active',
    'settings.update_credentials': 'Update your access credentials',
    'settings.identity_confirm': 'Institutional identity confirmation',
    'settings.fixed_label': 'Fixed',

    // Operations Page
    'ops.title': 'Start Operations',
    'ops.collect': 'Earnings Collection',
    'ops.collect_sub': 'Activate your servers to obtain daily profits.',
    'ops.system_status': 'System Status',
    'ops.processing': 'Processing...',
    'ops.completed': 'Completed',
    'ops.waiting': 'Waiting',
    'ops.synchronized': 'Synchronized',
    'ops.estimated': 'Estimated Yield',
    'ops.tasks_left': 'Tasks Remaining',
    'ops.btn_start': 'Start Operations',
    'ops.btn_finished': 'Work Completed',

    // Withdraw Page
    'common.fill_fields': 'Please fill in all required fields.',
    'withdraw.title': 'Request Withdrawal',
    'withdraw.amount': 'Withdrawal Amount',
    'withdraw.amount_placeholder': 'Enter amount (Min. 3,000 Kz)',
    'withdraw.min_error': 'The minimum withdrawal amount is 3,000 Kz',
    'withdraw.bank_acc': 'Bank Account',
    'withdraw.bank_placeholder': 'Select linked account',
    'withdraw.security_pass': 'Security Password',
    'withdraw.security_pass_placeholder': 'Enter login password',
    'withdraw.tax': 'Service Fee',
    'withdraw.net_total': 'Net Total',
    'withdraw.info_title': 'Withdrawal Information',
    'withdraw.info1': 'Processing in 5-60 minutes after approval.',
    'withdraw.info2': '14% fee for Microsoft Exchange ecosystem maintenance.',
    'withdraw.btn_confirm': 'Confirm Withdrawal',

    // Recharge Page
    'recharge.title': 'Recharge Account',
    'recharge.method': 'Recharge Method',
    'recharge.amount': 'Recharge Amount',
    'recharge.btn_confirm': 'Confirm Recharge',

    // Products Page
    'products.title': 'Products Cloud',
    'products.sub': 'High performance Microsoft licenses.',
    'products.price': 'Price',
    'products.daily': 'Daily Yield',
    'products.duration': 'Duration',
    'products.btn_buy': 'Buy',
    'products.my_purchases': 'My Purchases',

    // Recharge Page
    'recharge.suggested_amount': 'Suggested',
    'recharge.manual_amount': 'Enter Manual Amount',
    'recharge.min_error': 'Minimum recharge amount is 3,000 Kz',
    'recharge.max_error': 'Maximum recharge amount is 1,000,000 Kz',
    'recharge.select_bank_prompt': 'Please select a bank to recharge',
    'recharge.step_amount': 'Recharge Balance',
    'recharge.step_bank': 'Select Bank',
    'recharge.step_details': 'Deposit Details',
    'recharge.selected_bank': 'Selected Bank',
    'recharge.iban_payment': 'Payment IBAN',
    'recharge.beneficiary': 'Official Beneficiary',
    'recharge.deposit_value': 'Deposit Value',
    'recharge.history_title': 'Recharge history',
    'recharge.process_time': 'Processing Time',
    'recharge.process_info': 'Usually between 5 to 60 minutes after confirmation.',
    'recharge.disclaimer': 'By clicking finish, you declare that you are aware that you must perform the transfer via your bank app.',
    'recharge.btn_finish': 'Finish Recharge',
    'recharge.copy_toast': 'Copied to clipboard!',

    // Social Proof Page
    'social.title': 'Social Proof',
    'social.share_success': 'Share your success!',
    'social.share_sub': 'Send your withdrawal proof to motivate the community.',
    'social.photo_label': 'Proof Photo',
    'social.upload_btn': 'Upload proof image',
    'social.formats': 'Supported formats: JPG, PNG',
    'social.amount_label': 'Total Withdrawal Value (Kz)',
    'social.message_label': 'Your Message',
    'social.message_placeholder': 'Write a comment...',
    'social.send_btn': 'Send Official Proof',
    'social.history_info': 'Verified Payment History',
    'social.bonus_info': 'Publish your proof and win bonuses from 100 Kz up to 9,999 Kz.',
    'social.received': 'Received',
    'social.guarantee': 'Microsoft Exchange Guaranteed Payments',
    'social.proof1_comment': 'Successfully received! Microsoft Exchange really pays.',
    'social.proof2_comment': 'Fast withdrawal via IBAN. I recommend it to everyone!',

    // Password Page
    'password.title': 'Change Password',
    'password.old_label': 'Old Password',
    'password.old_placeholder': 'Confirm current password',
    'password.new_label': 'New Password',
    'password.new_placeholder': 'Minimum 8 characters',
    'password.confirm_label': 'Confirm New Password',
    'password.confirm_placeholder': 'Repeat new password',
    'password.match_error': 'New passwords do not match!',
    'password.success': 'Password changed successfully!',
    'password.btn_update': 'Update Password',

    // Auth Pages
    'auth.login': 'Sign in',
    'auth.enter_password': 'Enter password',
    'auth.phone_label': 'Phone Number',
    'auth.phone_placeholder': 'Enter number (9XXXXXXXX)',
    'auth.no_account': "Don't have an account?",
    'auth.create_one': 'Create one!',
    'auth.password_label': 'Password',
    'auth.password_placeholder': 'Enter password',
    'auth.forgot_password': 'Forgot password?',
    'auth.phone_error_empty': 'Please enter the number',
    'auth.phone_error_format': 'Invalid number for local format',
    'auth.phone_error_length': 'Number must have 9 digits',
    'auth.password_error_empty': 'Please enter the password',
    'auth.password_error_length': 'Password must have 8 or more characters',
    'auth.welcome_back': 'Welcome back!',
    'auth.signup': 'Sign up',
    'auth.signup_title': 'Create account',
    'auth.invite_code': 'Invite Code',
    'auth.invite_placeholder': 'Enter code (INV-XXXXX)',
    'auth.has_account': 'Already have an account?',
    'auth.captcha_label': 'Captcha Validation',
    'auth.captcha_placeholder': 'Captcha code',
    'auth.password_signup_placeholder': 'At least 8 characters',
    'auth.btn_register': 'Register',
    'auth.phone_error_invalid': 'This phone number seems invalid',
    'auth.captcha_error_empty': 'Please fill in the CAPTCHA verification',
    'auth.captcha_error_wrong': 'Incorrect CAPTCHA code. Try again.',
    'auth.invite_error_empty': 'Please enter the invite code',
    'auth.password_error_simple': 'Password too simple. Please choose a more secure password.',
    'auth.password_error_complexity': 'Password must contain letters and numbers',
    'auth.signup_success': 'Account created successfully!',

    // About Page
    'about.header': 'About Microsoft Exchange',
    'about.hero_title': 'We believe in what\'s possible.',
    'about.hero_sub': 'Explore how Microsoft technology is empowering people around the world to create the future they want.',
    'about.vision_label': 'Overview',
    'about.vision_title': 'Leading global digital transformation.',
    'about.vision_p1': 'Microsoft Exchange is a driving force in global technological innovation. We evolved from a software company to a leader in intelligent cloud services.',
    'about.vision_p2': 'With pioneering advances in AI, we offer the tools necessary for organizations to transform their productivity.',
    'about.local_title': 'Local Platform and Ecosystem',
    'about.local_p1': 'Users in Angola can now access our services and join our company\'s official ecosystem.',
    'about.commitments': 'Our Commitments',
    'about.mission_title': 'Our Mission',
    'about.mission_desc': 'Empower every person and every organization on the planet to achieve more through technology.',
    'about.stat_foundation': 'Foundation',
    'about.stat_countries': 'Countries',
    'about.stat_people': 'People',
    'about.stat_licenses': 'Licenses',
    'about.quote': '"Our journey is about building technology so that others can build more technology."',
    'about.rights': '© 2026 Microsoft Exchange. All rights reserved.',

    // Support Page
    'support.header': 'Microsoft Support',
    'support.hero_title': 'How can we help?',
    'support.search_placeholder': 'Type here to search official help...',
    'support.whatsapp_title': 'Join WhatsApp Group',
    'support.whatsapp_desc': 'Official community of investors and bonuses.',
    'support.manager_title': 'Dedicated Manager (Community)',
    'support.manager_desc': 'VIP support for team leaders.',
    'support.tech_title': 'Talk to Technical Support',
    'support.tech_desc': 'We are here to help 24 hours a day.',
    'support.security_title': 'Your security is our priority',
    'support.security_desc': 'All support interactions are encrypted and verified by Microsoft.',

    // Identity Page
    'identity.header': 'Identity Verification',
    'identity.hero_title': 'Authentication',
    'identity.hero_sub': 'Confirm your identity to ensure account security and comply with Microsoft Exchange guidelines.',
    'identity.name_label': 'Full Name (as on ID)',
    'identity.name_placeholder': 'Enter your full name',
    'identity.id_label': 'ID or Passport Number',
    'identity.id_placeholder': 'Enter document number',
    'identity.province_label': 'Province of Residence',
    'identity.province_placeholder': 'Select your province',
    'identity.job_label': 'Current Occupation',
    'identity.job_placeholder': 'Select your occupation',
    'identity.btn_send': 'Send for Verification',
    'identity.info_title': 'Why is this necessary?',
    'identity.info_desc': 'Identity authentication helps us prevent fraud and protect your financial assets. Your data is encrypted.',
    'identity.secure_server': 'Microsoft Secure Server',
    'identity.success': 'Information sent for review!',
    'identity.error_name': 'Please enter your full name',
    'identity.error_id': 'Please enter ID or Passport number',
    'identity.error_province': 'Please select your province',
    'identity.error_job': 'Please select your occupation',
    'identity.job_unemployed': 'Unemployed',
    'identity.job_public': 'Public Employee',
    'identity.job_private': 'Private Sector Employee',
    'identity.job_merchant': 'Merchant',

    // Team Page
    'team.header': 'My Team',
    'team.stats_total': 'Total Members',
    'team.stats_com': 'Team Commissions',
    'team.level1': '1st Level',
    'team.level2': '2nd Level',
    'team.level3': '3rd Level',
    'team.search_placeholder': 'Search member...',
    'team.member_since': 'Member since',
    'team.active': 'Active',
    'team.inactive': 'Inactive',
    'team.empty': 'Waiting for new members',

    // FAQ Page
    'faq.header': 'Frequently Asked Questions',
    'faq.hero_title': 'Technical Help',
    'faq.hero_sub': 'Find guides and answers about the platform.',
    'faq.feedback_useful': 'Was this information useful?',
    'faq.yes': 'Yes',
    'faq.no': 'No',
    'faq.feedback_thanks': 'Thank you for your feedback!',
    'faq.q1': 'How to recharge my account?',
    'faq.q2': 'How to withdraw my earnings?',
    'faq.q3': 'How to complete the daily task?',
    'faq.q4': 'What is the duration of products?',
    'faq.q5': 'How does the platform work?',
    'faq.q6': 'How to use support?',
    'faq.q7': 'Team earnings?',

    // Products Details
    'products.active_badge': 'Active',
    'products.daily_income': 'Daily Income',
    'products.total_price': 'Final Price',
    'products.available_now': 'Available for immediate deployment',
    'products.os_version': 'OS Version',
    'products.cloud_space': 'Cloud Space',
    'products.product_id': 'Product ID',
    'products.overview': 'Overview',
    'products.specs': 'Specifications',
    'products.activation': 'Activation',
    'products.expiration': 'Expiration',
    'products.secure_payment': 'Secure payment processed through regional gateway.',
    'products.tech_support_24h': 'Technical support available 24h.',
    'products.not_found': 'Product not found',
    'products.back_to_list': 'Back to Products',
    'products.buy_success': 'acquired successfully!',

    // Specific Product Data
    'product.win7.name': 'Windows 7',
    'product.win7.version': 'Professional Edition',
    'product.win7.desc': 'The classic Windows 7 experience, cloud-optimized. Stability and performance for your daily operations.',
    'product.win7.feat1': 'Aero Glass Interface',
    'product.win7.feat2': 'Fast navigation',
    'product.win7.feat3': 'Legacy app support',
    'product.win7.feat4': 'Advanced security',

    'product.win8.name': 'Windows 8',
    'product.win8.version': 'Enterprise V2',
    'product.win8.desc': 'Modern design with dynamic tiles. Windows 8 Enterprise offers powerful management tools for your team.',
    'product.win8.feat1': 'Dynamic start screen',
    'product.win8.feat2': 'Touch optimized',
    'product.win8.feat3': 'Enhanced multitasking',
    'product.win8.feat4': 'Official ISO included',

    'product.win10.name': 'Windows 10',
    'product.win10.version': 'Cloud Server Base',
    'product.win10.desc': 'The gold standard of modern computing. Cloud Server version with high availability and server resources.',
    'product.win10.feat1': 'Classic Start Menu',
    'product.win10.feat2': 'Integrated Cortana',
    'product.win10.feat3': 'Microsoft Edge',
    'product.win10.feat4': 'Dedicated Cloud Environment',

    'product.win11.name': 'Windows 11',
    'product.win11.version': 'NextGen AI Core',
    'product.win11.desc': 'The latest generation of Windows. With integrated AI features to maximize your profits and efficiency.',
    'product.win11.feat1': 'New centered design',
    'product.win11.feat2': 'Integrated widgets',
    'product.win11.feat3': 'Superior performance',
    'product.win11.feat4': 'Copilot AI Pre-installed',

    'product.unit.day': 'day',
    'product.unit.days': 'days',

    // Invite Page
    'invite.title': 'Invite Friends',
    'invite.team_btn': 'My Team',
    'invite.partnership': 'Partnership Network',
    'invite.link_label': 'Invite Link',
    'invite.code_label': 'Invite Code',
    'invite.btn_share': 'Share Now',
    'invite.toast_share': 'Sharing options opened!',
    'invite.copy_toast': 'Copied to clipboard!',

    // Coupons
    'coupons.title': 'Coupon Redemption',
    'coupons.hero_title': 'Activate Bonus',
    'coupons.hero_sub': 'Enter the promo code provided by your manager or in official groups.',
    'coupons.label': 'Coupon Code',
    'coupons.placeholder': 'Enter the code',
    'coupons.btn': 'Redeem Now',
    'coupons.error_invalid': 'Please enter a valid coupon code.',

    // History / Licenses
    'history.title': 'My Licenses',
    'history.loading': 'Synchronizing with Microsoft servers...',
    'history.empty': 'No active licenses found.',
    'history.license_id': 'License ID',
    'history.activated_at': 'Activated on',
    'history.investment': 'Investment',
    'history.status': 'Status',
    'history.status_active': 'Active & Earning',
    'history.status_expired': 'Expired',
    'history.remaining': 'Remaining Duration',
    'history.manage_server': 'Download Setup',
    'history.backup_iso': 'MB',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.invite': 'Inviter',
    'nav.profile': 'Profil',

    // Common
    'common.copy': 'Copier',
    'common.copied': 'Copié',
    'common.confirm': 'Confirmer',
    'common.cancel': 'Annuler',
    'common.next': 'Suivant',
    'common.prev': 'Précédent',
    'common.back': 'Retour',
    'common.close': 'Fermer',
    'common.send': 'Envoyer',
    'common.save': 'Enregistrer',
    'common.loading': 'Chargement...',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.warning': 'Avertissement',
    'common.status': 'Statut',
    'common.verified': 'Vérifié',

    // Home Page
    'home.welcome_hero': 'Bienvenue sur Exchange Experience',
    'home.hero_sub': 'Commencez votre voyage avec l\'infrastructure la plus robuste du marché.',
    'home.users': 'Utilisateurs',
    'home.secure': 'Sécurisé',
    'home.servers': 'Serveurs',
    'home.news': 'Nouvelles',
    'home.social_proof': 'Preuves de retrait',
    'home.doubts': 'Des doutes?',
    'home.support_cta': 'Contactez notre support partenaire Microsoft officiel disponible 24h/24.',
    'home.support_btn': 'Accéder au support',
    'home.marquee': 'Bienvenue sur Microsoft Exchange Angola ! Profitez de nos offres de serveurs exclusives pour booster votre rendement quotidien. Restez à l\'écoute de nos mises à jour officielles.',
    'home.announcement.title1': 'Bienvenue sur Microsoft Exchange Angola',
    'home.announcement.content1': 'Votre voyage vers l\'indépendance financière commence ici. Microsoft Exchange Technologie propose l\'infrastructure cloud la plus sécurisée.',
    'home.announcement.title2': 'Système d\'invitation et revenus d\'équipe',
    'home.announcement.content2': 'Gagnez des bonus sur 3 niveaux en invitant vos amis et votre famille dans notre communauté.',
    'home.announcement.title3': 'Communauté Microsoft officielle',
    'home.announcement.content3': 'Rejoignez notre WhatsApp pour les preuves de paiement et un support technique prioritaire.',
    'home.community_btn': 'Rejoindre la communauté',

    // Profile Page
    'profile.title': 'Profil de l\'utilisateur',
    'profile.balance': 'Solde Total',
    'profile.recharge': 'Recharger',
    'profile.withdraw': 'Retirer',
    'profile.operations': 'Démarrer les opérations',
    'profile.team': 'Mon Équipe',
    'profile.history': 'Historique Général',
    'profile.auth': 'Authentifier le compte',
    'profile.bank_link': 'Liaison Bancaire',
    'profile.bank_info': 'Informations Bancaires',
    'profile.coupons': 'Utiliser des Coupons',
    'profile.about': 'À propos de Microsoft Exchange',
    'profile.settings': 'Paramètres',
    'profile.logout': 'Déconnexion',
    'profile.recharge_usdt': 'Recharge USDT',
    'profile.user_cloud': 'Utilisateur Microsoft Exchange',
    'profile.moeda_local': 'Monnaie Locale',
    'profile.crypto_digital': 'Crypto Digitale',

    // Settings Page
    'settings.title': 'Paramètres du compte',
    'settings.hero_sub': 'Gérez vos détails de sécurité, votre vérification officielle et vos connexions réseau Microsoft Exchange.',
    'settings.language': 'Langue',
    'settings.change_password': 'Changer le mot de passe',
    'settings.authenticate': 'Authentifier le compte',
    'settings.phone': 'Téléphone lié',
    'settings.invite_code': 'Code d\'invitation',
    'settings.security_personalization': 'Sécurité & Personnalisation',
    'settings.network_info': 'Informations réseau',
    'settings.help_title': 'Aide Exchange',
    'settings.lost_access': 'Accès perdu?',
    'settings.lost_access_sub': 'Récupérez votre compte en utilisant le processus de vérification officiel de Microsoft.',
    'settings.support_tech': 'Support technique',
    'settings.support_tech_sub': 'Contactez notre équipe spécialisée en infrastructure cloud.',
    'settings.recovery_btn': 'Démarrer la récupération',
    'settings.support_btn': 'Parler au support',
    'settings.logout': 'Déconnexion',
    'settings.active_status': 'Statut : Actif',
    'settings.update_credentials': 'Mettez à jour vos identifiants d\'accès',
    'settings.identity_confirm': 'Confirmation d\'identité institutionnelle',
    'settings.fixed_label': 'Fixe',

    // Operations Page
    'ops.title': 'Démarrer les opérations',
    'ops.collect': 'Collecte des gains',
    'ops.collect_sub': 'Activez vos serveurs pour obtenir des profits quotidiens.',
    'ops.system_status': 'Statut du système',
    'ops.processing': 'Traitement...',
    'ops.completed': 'Terminé',
    'ops.waiting': 'En attente',
    'ops.synchronized': 'Synchronisé',
    'ops.estimated': 'Rendement estimé',
    'ops.tasks_left': 'Tâches restantes',
    'ops.btn_start': 'Démarrer les opérations',
    'ops.btn_finished': 'Travail terminé',

    // Withdraw Page
    'common.fill_fields': 'Veuillez remplir tous les champs obligatoires.',
    'withdraw.title': 'Demander un retrait',
    'withdraw.amount': 'Montant du retrait',
    'withdraw.amount_placeholder': 'Saisir le montant (Min. 3 000 Kz)',
    'withdraw.min_error': 'Le montant minimum de retrait est de 3 000 Kz',
    'withdraw.bank_acc': 'Compte bancaire',
    'withdraw.bank_placeholder': 'Sélectionner le compte lié',
    'withdraw.security_pass': 'Mot de passe de sécurité',
    'withdraw.security_pass_placeholder': 'Saisir le mot de passe de connexion',
    'withdraw.tax': 'Frais de service',
    'withdraw.net_total': 'Total Net',
    'withdraw.info_title': 'Informations sur le retrait',
    'withdraw.info1': 'Traitement en 5 à 60 minutes après approbation.',
    'withdraw.info2': 'Frais de 14% pour la maintenance de l\'écosystème Microsoft Exchange.',
    'withdraw.btn_confirm': 'Confirmer le retrait',

    // Recharge Page
    'recharge.title': 'Recharger le compte',
    'recharge.method': 'Méthode de recharge',
    'recharge.amount': 'Montant de la recharge',
    'recharge.btn_confirm': 'Confirmer la recharge',

    // Products Page
    'products.title': 'Nuage de Produits',
    'products.sub': 'Licences Microsoft haute performance.',
    'products.price': 'Prix',
    'products.daily': 'Rendement Quotidien',
    'products.duration': 'Durée',
    'products.btn_buy': 'Acheter',
    'products.my_purchases': 'Mes Achats',

    // Recharge Page
    'recharge.suggested_amount': 'Suggestions',
    'recharge.manual_amount': 'Saisir le montant manuel',
    'recharge.min_error': 'Le montant minimum de recharge est de 3 000 Kz',
    'recharge.max_error': 'Le montant maximum de recharge est de 1 000 000 Kz',
    'recharge.select_bank_prompt': 'Veuillez sélectionner une banque pour recharger',
    'recharge.step_amount': 'Recharger le solde',
    'recharge.step_bank': 'Sélectionner la banque',
    'recharge.step_details': 'Détails du dépôt',
    'recharge.selected_bank': 'Banque sélectionnée',
    'recharge.iban_payment': 'IBAN de paiement',
    'recharge.beneficiary': 'Bénéficiaire officiel',
    'recharge.deposit_value': 'Valeur du dépôt',
    'recharge.history_title': 'Historique des recharges',
    'recharge.process_time': 'Temps de traitement',
    'recharge.process_info': 'Généralement entre 5 et 60 minutes après confirmation.',
    'recharge.disclaimer': 'En cliquant sur terminer, vous déclarez être conscient que vous devez effectuer le transfert via votre application bancaire.',
    'recharge.btn_finish': 'Terminer la recharge',
    'recharge.copy_toast': 'Copié dans le presse-papier!',

    // Social Proof Page
    'social.title': 'Preuves Sociales',
    'social.share_success': 'Partagez votre succès !',
    'social.share_sub': 'Envoyez votre preuve de retrait pour motiver la communauté.',
    'social.photo_label': 'Photo de la preuve',
    'social.upload_btn': 'Charger l\'image de preuve',
    'social.formats': 'Formats supportés : JPG, PNG',
    'social.amount_label': 'Valeur totale du retrait (Kz)',
    'social.message_label': 'Votre Message',
    'social.message_placeholder': 'Écrire un commentaire...',
    'social.send_btn': 'Envoyer la preuve officielle',
    'social.history_info': 'Historique des paiements vérifiés',
    'social.bonus_info': 'Publiez votre preuve et gagnez des bonus de 100 Kz à 9 999 Kz.',
    'social.received': 'Reçu',
    'social.guarantee': 'Paiements garantis Microsoft Exchange',
    'social.proof1_comment': 'Reçu avec succès ! Microsoft Exchange paie vraiment.',
    'social.proof2_comment': 'Retrait rapide via IBAN. Je le recommande à tout le monde !',

    // Password Page
    'password.title': 'Changer le mot de passe',
    'password.old_label': 'Ancien mot de passe',
    'password.old_placeholder': 'Confirmer le mot de passe actuel',
    'password.new_label': 'Nouveau mot de passe',
    'password.new_placeholder': '8 caractères minimum',
    'password.confirm_label': 'Confirmer le nouveau mot de passe',
    'password.confirm_placeholder': 'Répéter le nouveau mot de passe',
    'password.match_error': 'Les nouveaux mots de passe ne correspondent pas !',
    'password.success': 'Mot de passe modifié avec succès !',
    'password.btn_update': 'Mettre à jour le mot de passe',

    // Auth Pages
    'auth.login': 'Se connecter',
    'auth.enter_password': 'Saisir le mot de passe',
    'auth.phone_label': 'Numéro de téléphone',
    'auth.phone_placeholder': 'Saisir le numéro (9XXXXXXXX)',
    'auth.no_account': 'Pas de compte ?',
    'auth.create_one': 'Créez-en un !',
    'auth.password_label': 'Mot de passe',
    'auth.password_placeholder': 'Saisir le mot de passe',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.phone_error_empty': 'Veuillez saisir le numéro',
    'auth.phone_error_format': 'Numéro invalide pour le format local',
    'auth.phone_error_length': 'Le numéro doit avoir 9 chiffres',
    'auth.password_error_empty': 'Veuillez saisir le mot de passe',
    'auth.password_error_length': 'Le mot de passe doit avoir 8 caractères ou plus',
    'auth.welcome_back': 'Bon retour !',
    'auth.signup': 'Inscription',
    'auth.signup_title': 'Créer un compte',
    'auth.invite_code': 'Code d\'invitation',
    'auth.invite_placeholder': 'Saisir le code (INV-XXXXX)',
    'auth.has_account': 'Vous avez déjà un compte ?',
    'auth.captcha_label': 'Validation Captcha',
    'auth.captcha_placeholder': 'Code captcha',
    'auth.password_signup_placeholder': 'Au moins 8 caractères',
    'auth.btn_register': 'S\'inscrire',
    'auth.phone_error_invalid': 'Ce numéro de téléphone semble invalide',
    'auth.captcha_error_empty': 'Veuillez remplir la vérification CAPTCHA',
    'auth.captcha_error_wrong': 'Code CAPTCHA incorrect. Réessayez.',
    'auth.invite_error_empty': 'Veuillez saisir le code d\'invitation',
    'auth.password_error_simple': 'Mot de passe trop simple. Veuillez choisir un mot de passe plus sûr.',
    'auth.password_error_complexity': 'Le mot de passe doit contenir des lettres et des chiffres',
    'auth.signup_success': 'Compte créé avec succès !',

    // About Page
    'about.header': 'À propos de Microsoft Exchange',
    'about.hero_title': 'Nous croyons en ce qui est possible.',
    'about.hero_sub': 'Découvrez comment la technologie Microsoft permet aux individus du monde entier de créer l\'avenir qu\'ils souhaitent.',
    'about.vision_label': 'Aperçu',
    'about.vision_title': 'Mener la transformation numérique mondiale.',
    'about.vision_p1': 'Microsoft Exchange est une force motrice de l\'innovation technologique mondiale. Nous sommes passés d\'une société de logiciels à un leader des services cloud intelligents.',
    'about.vision_p2': 'Grâce à des avancées pionnières en IA, nous proposons les outils nécessaires aux organisations pour transformer leur productivité.',
    'about.local_title': 'Plateforme et écosystème locaux',
    'about.local_p1': 'Les utilisateurs en Angola peuvent désormais accéder à nos services et rejoindre l\'écosystème officiel de notre entreprise.',
    'about.commitments': 'Nos Engagements',
    'about.mission_title': 'Notre Mission',
    'about.mission_desc': 'Donner à chaque personne et à chaque organisation sur la planète les moyens d\'accomplir davantage grâce à la technologie.',
    'about.stat_foundation': 'Fondation',
    'about.stat_countries': 'Pays',
    'about.stat_people': 'Personnes',
    'about.stat_licenses': 'Licences',
    'about.quote': '"Notre voyage consiste à construire de la technologie pour que d\'autres puissent construire plus de technologie."',
    'about.rights': '© 2026 Microsoft Exchange. Tous droits réservés.',

    // Support Page
    'support.header': 'Support Microsoft',
    'support.hero_title': 'Comment pouvons-nous vous aider ?',
    'support.search_placeholder': 'Tapez ici pour rechercher l\'aide officielle...',
    'support.whatsapp_title': 'Rejoindre le groupe WhatsApp',
    'support.whatsapp_desc': 'Communauté officielle des investisseurs et bonus.',
    'support.manager_title': 'Gestionnaire dédié (Communauté)',
    'support.manager_desc': 'Support VIP pour les chefs d\'équipe.',
    'support.tech_title': 'Parler au support technique',
    'support.tech_desc': 'Nous sommes là pour vous aider 24h/24.',
    'support.security_title': 'Votre sécurité est notre priorité',
    'support.security_desc': 'Toutes les interactions de support sont cryptées et vérifiées par Microsoft.',

    // Identity Page
    'identity.header': 'Vérification d\'identité',
    'identity.hero_title': 'Authentification',
    'identity.hero_sub': 'Confirmez votre identité pour assurer la sécurité de votre compte et vous conformer aux directives de Microsoft Exchange.',
    'identity.name_label': 'Nom complet (tel que sur la pièce d\'identité)',
    'identity.name_placeholder': 'Saisissez votre nom complet',
    'identity.id_label': 'Numéro d\'identité ou de passeport',
    'identity.id_placeholder': 'Saisissez le numéro du document',
    'identity.province_label': 'Province de résidence',
    'identity.province_placeholder': 'Sélectionnez votre province',
    'identity.job_label': 'Profession actuelle',
    'identity.job_placeholder': 'Sélectionnez votre profession',
    'identity.btn_send': 'Envoyer pour vérification',
    'identity.info_title': 'Pourquoi est-ce nécessaire ?',
    'identity.info_desc': 'L\'authentification d\'identité nous aide à prévenir la fraude et à protéger vos actifs financiers. Vos données sont cryptées.',
    'identity.secure_server': 'Serveur sécurisé Microsoft',
    'identity.success': 'Informations envoyées pour examen !',
    'identity.error_name': 'Veuillez saisir votre nom complet',
    'identity.error_id': 'Veuillez saisir le numéro d\'identité ou de passeport',
    'identity.error_province': 'Veuillez sélectionner votre province',
    'identity.error_job': 'Veuillez sélectionner votre profession',
    'identity.job_unemployed': 'Sans emploi',
    'identity.job_public': 'Employé public',
    'identity.job_private': 'Employé du secteur privé',
    'identity.job_merchant': 'Commerçant',

    // Team Page
    'team.header': 'Mon Équipe',
    'team.stats_total': 'Total des Membres',
    'team.stats_com': 'Commissions d\'Équipe',
    'team.level1': '1er Niveau',
    'team.level2': '2e Niveau',
    'team.level3': '3e Niveau',
    'team.search_placeholder': 'Rechercher un membre...',
    'team.member_since': 'Membre depuis',
    'team.active': 'Actif',
    'team.inactive': 'Inactif',
    'team.empty': 'En attente de nouveaux membres',

    // FAQ Page
    'faq.header': 'Questions Fréquentes',
    'faq.hero_title': 'Aide technique',
    'faq.hero_sub': 'Trouvez des guides et des réponses sur la plateforme.',
    'faq.feedback_useful': 'Ces informations ont-elles été utiles ?',
    'faq.yes': 'Oui',
    'faq.no': 'Non',
    'faq.feedback_thanks': 'Merci pour votre commentaire !',
    'faq.q1': 'Comment recharger mon compte ?',
    'faq.q2': 'Comment retirer mes gains ?',
    'faq.q3': 'Comment accomplir la tâche quotidienne ?',
    'faq.q4': 'Quelle est la durée des produits ?',
    'faq.q5': 'Comment fonctionne la plateforme ?',
    'faq.q6': 'Comment utiliser le support ?',
    'faq.q7': 'Gains par équipe ?',

    // Products Details
    'products.active_badge': 'Actif',
    'products.daily_income': 'Revenu Quotidien',
    'products.total_price': 'Prix Final',
    'products.available_now': 'Disponible pour un déploiement immédiat',
    'products.os_version': 'Version de l\'OS',
    'products.cloud_space': 'Espace Cloud',
    'products.product_id': 'ID du Produit',
    'products.overview': 'Aperçu',
    'products.specs': 'Spécifications',
    'products.activation': 'Activation',
    'products.expiration': 'Expiration',
    'products.secure_payment': 'Paiement sécurisé via passerelle régionale.',
    'products.tech_support_24h': 'Support technique disponible 24h/24.',
    'products.not_found': 'Produit non trouvé',
    'products.back_to_list': 'Retour aux Produits',
    'products.buy_success': 'acquis avec succès !',

    // Specific Product Data
    'product.win7.name': 'Windows 7',
    'product.win7.version': 'Professional Edition',
    'product.win7.desc': 'L\'expérience classique de Windows 7, optimisée pour le cloud. Stabilité et performances pour vos opérations quotidiennes.',
    'product.win7.feat1': 'Interface Aero Glass',
    'product.win7.feat2': 'Navigation rapide',
    'product.win7.feat3': 'Support apps héritées',
    'product.win7.feat4': 'Sécurité avancée',

    'product.win8.name': 'Windows 8',
    'product.win8.version': 'Enterprise V2',
    'product.win8.desc': 'Design moderne avec tuiles dynamiques. Windows 8 Enterprise offre des outils de gestion puissants.',
    'product.win8.feat1': 'Écran d\'accueil dynamique',
    'product.win8.feat2': 'Optimisé tactile',
    'product.win8.feat3': 'Multitâche amélioré',
    'product.win8.feat4': 'ISO officiel inclus',

    'product.win10.name': 'Windows 10',
    'product.win10.version': 'Cloud Server Base',
    'product.win10.desc': 'La référence de l\'informatique moderne. Version Cloud Server avec haute disponibilité.',
    'product.win10.feat1': 'Menu Démarrer classique',
    'product.win10.feat2': 'Cortana intégrée',
    'product.win10.feat3': 'Microsoft Edge',
    'product.win10.feat4': 'Environnement Cloud dédié',

    'product.win11.name': 'Windows 11',
    'product.win11.version': 'NextGen AI Core',
    'product.win11.desc': 'La dernière génération de Windows. Avec des fonctionnalités d\'IA pour maximiser vos profits.',
    'product.win11.feat1': 'Nouveau design centré',
    'product.win11.feat2': 'Widgets intégrés',
    'product.win11.feat3': 'Performances supérieures',
    'product.win11.feat4': 'Copilot AI pré-installé',

    'product.unit.day': 'jour',
    'product.unit.days': 'jours',

    // Invite Page
    'invite.title': 'Inviter des Amis',
    'invite.team_btn': 'Mon Équipe',
    'invite.partnership': 'Réseau de Partenariat',
    'invite.link_label': 'Lien d\'Invitation',
    'invite.code_label': 'Code d\'Invitation',
    'invite.btn_share': 'Partager Maintenant',
    'invite.toast_share': 'Options de partage ouvertes !',
    'invite.copy_toast': 'Copié dans le presse-papier !',

    // Coupons
    'coupons.title': 'Utiliser un Coupon',
    'coupons.hero_title': 'Activer le Bonus',
    'coupons.hero_sub': 'Saisissez le code promo fourni par votre gestionnaire ou dans les groupes officiels.',
    'coupons.label': 'Code du Coupon',
    'coupons.placeholder': 'Saisissez le code',
    'coupons.btn': 'Utiliser Maintenant',
    'coupons.error_invalid': 'Veuillez saisir un code de coupon valide.',

    // History / Licenses
    'history.title': 'Mes Licences',
    'history.loading': 'Synchronisation avec les serveurs Microsoft...',
    'history.empty': 'Aucune licence active trouvée.',
    'history.license_id': 'ID de Licence',
    'history.activated_at': 'Activé le',
    'history.investment': 'Investissement',
    'history.status': 'Statut',
    'history.status_active': 'Actif et Rentable',
    'history.status_expired': 'Expiré',
    'history.remaining': 'Durée Restante',
    'history.manage_server': 'Gérer le Serveur',
    'history.backup_iso': 'Sauvegarde ISO',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Inicializar com o idioma salvo ou padrão 'pt'
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language') as Language;
    return (saved === 'pt' || saved === 'en' || saved === 'fr') ? saved : 'pt';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
